Doppler.BillingUser/Startup.cs

[NO-TICKET] - Add CORS

---

Doppler.BillingUser.Test/BillingInformationValidatorTest.cs
Doppler.BillingUser.Test/PutBillingControllerTest.cs
Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Doppler.BillingUser.csproj
Doppler.BillingUser/Infrastructure/BillingRepository.cs
Doppler.BillingUser/Infrastructure/IBillingRepository.cs
Doppler.BillingUser/Startup.cs
Doppler.BillingUser/Validators/BillingInformationValidator.cs

We add a new endpoint to update billing information with a PUT method, also we add validators for billing information properties
```
{
firstname: string;
lastname: string;
address: string;
city: string;
province: string;
country: string;
zipCode: string;
phone: string;
}
```

feat: [DAT-514] Add endpoint to update billing information

---

Doppler.BillingUser.Test/Doppler.BillingUser.Test.csproj
Doppler.BillingUser/Doppler.BillingUser.csproj
package.json
yarn.lock

Update Dependabot dependencies

chore: update dependabot dependencies

---

Doppler.BillingUser.Test/PutCurrentPaymentMethodTest.cs
Doppler.BillingUser/ExternalServices/Sap/SapHelper.cs
Doppler.BillingUser/Infrastructure/BillingRepository.cs
Doppler.BillingUser/Model/User.cs

We need to set first name with user->firstname when the user does not user->BillingFirstname and user->RazonSocial

fix: [DAT-603] Fix FirstName empty when send to sap data

---

Doppler.BillingUser.Test/GetInvoiceRecipientsTest.cs
Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Infrastructure/BillingRepository.cs
Doppler.BillingUser/Infrastructure/IBillingRepository.cs
Doppler.BillingUser/Model/EmailRecipients.cs

We need to get email invoice recipients to send to webapp
examples:

feat: [DAT-625] Add get invoice recipients endpoint

---

Doppler.BillingUser.Test/RelayEmailSenderTest.cs
Doppler.BillingUser/Doppler.BillingUser.csproj
Doppler.BillingUser/ExternalServices/EmailSender/Attachment.cs
Doppler.BillingUser/ExternalServices/EmailSender/IEmailSender.cs
Doppler.BillingUser/ExternalServices/EmailSender/RelayEmailSender.cs
Doppler.BillingUser/ExternalServices/EmailSender/RelayEmailSenderConfiguration.cs
Doppler.BillingUser/Startup.cs
Doppler.BillingUser/appsettings.Development.json
Doppler.BillingUser/appsettings.json

Here we are adding an Email Sender, and we implement it to send by Relay.

[DAT-693] - Add email sender

---

Doppler.BillingUser.Test/RelayEmailSenderTest.cs
Doppler.BillingUser/ExternalServices/EmailSender/RelayEmailSender.cs
Doppler.BillingUser/ExternalServices/EmailSender/RelayEmailSenderSettings.cs
Doppler.BillingUser/Startup.cs
Doppler.BillingUser/appsettings.Development.json
Doppler.BillingUser/appsettings.json

[DAT-693] - Fix settings section name

---

Doppler.BillingUser.Test/PutCurrentPaymentMethodTest.cs
Doppler.BillingUser.Test/PutInvoiceRecipientsTest.cs
Doppler.BillingUser.Test/SapServiceTest.cs
Doppler.BillingUser/ExternalServices/Sap/SapService.cs

We use HttpClientfactory to send a request to SAP service, with this pull request we use Flurl client to send POST requests to Sap service

feat: [DAT-713] Add Flurl client for SAP service

---

Doppler.BillingUser.Test/GetCurrentPaymentMethodTest.cs
Doppler.BillingUser.Test/PostAgreementTest.cs
Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Enums/UserTypeEnum.cs
Doppler.BillingUser/ExternalServices/FirstData/IPaymentGateway.cs
Doppler.BillingUser/ExternalServices/FirstData/PaymentGateway.cs
Doppler.BillingUser/Infrastructure/BillingRepository.cs
Doppler.BillingUser/Infrastructure/IBillingRepository.cs
Doppler.BillingUser/Infrastructure/IUserRepository.cs
Doppler.BillingUser/Infrastructure/InfrastructureServiceCollectionExtensions.cs
Doppler.BillingUser/Infrastructure/UserRepository.cs
Doppler.BillingUser/Model/AgreementInformation.cs
Doppler.BillingUser/Model/BillingCredit.cs
Doppler.BillingUser/Model/BillingCreditModel.cs
Doppler.BillingUser/Model/CreateAgreement.cs
Doppler.BillingUser/Model/PaymentMethod.cs
Doppler.BillingUser/Model/UserBillingInformation.cs
Doppler.BillingUser/Model/UserTypePlanInformation.cs
Doppler.BillingUser/Startup.cs
Doppler.BillingUser/Validators/AgreementInformationValidator.cs

new checkout support to buy credits for free users

Dat 578 prepaid for free users

---

Doppler.BillingUser.Test/PostAgreementTest.cs
Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/ExternalServices/Sap/SapBillingDto.cs
Doppler.BillingUser/ExternalServices/Sap/SapService.cs
Doppler.BillingUser/Infrastructure/BillingRepository.cs
Doppler.BillingUser/Infrastructure/IBillingRepository.cs
Doppler.BillingUser/Infrastructure/UserRepository.cs
Doppler.BillingUser/Model/BillingCredit.cs
Doppler.BillingUser/Model/UserBillingInformation.cs

send the invoice created during the checkout process to sap

Dat 715 ingregate send invoice to sap

---

Doppler.BillingUser/appsettings.Development.json
Doppler.BillingUser/appsettings.int.json
Doppler.BillingUser/appsettings.json
Doppler.BillingUser/appsettings.qa.json

We need to fix parameters for promocode and discountId from query

fix: [DAT-678] Fix calculate url parameters

---

Doppler.BillingUser/Infrastructure/BillingRepository.cs

Fix name of column in Billing credit table

fix: [DAT-678] fix name of idPromotion in insert biling credit sql sentence

---

Doppler.BillingUser/Infrastructure/BillingRepository.cs
Doppler.BillingUser/Model/Promotion.cs

Assign the ExtraCreditsPromotion in the BillingCredits
**Task:** [DAT-725](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-725)

[DAT-725] - Assign the ExtraCreditsPromotion in the BillingCredits

---

Doppler.BillingUser.Test/PostAgreementTest.cs
Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Infrastructure/IPromotionRepository.cs
Doppler.BillingUser/Infrastructure/PromotionRepository.cs
Doppler.BillingUser/Startup.cs

We need to increment/decrement the times to use for promocode

feat: [DAT-702] Add Increment/decrement for promocode in create agreement

---

Doppler.BillingUser/Infrastructure/BillingRepository.cs

Add check when the promotion is null

fix: when the promotion is null

---

Doppler.BillingUser/Controllers/BillingController.cs

fix issue when send planType to sap

fix: send planType to sap

---

Doppler.BillingUser.Test/PostAgreementTest.cs
Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/ExternalServices/Slack/ISlackService.cs
Doppler.BillingUser/ExternalServices/Slack/SlackService.cs
Doppler.BillingUser/ExternalServices/Slack/SlackSettings.cs
Doppler.BillingUser/Startup.cs
Doppler.BillingUser/appsettings.json

We need to notify in Slack chats when create agreement flow return an exception
PROD:
app: new-checkout-monitor
channel: new-checkout-monitor
QA:
app: new-checkout-QA-monitor
channel: new-checkout-QA-monitor
INT:
app: new-checkout-INT-monitor
channel: new-checkout-INT-monitor

feat: [DAT-722] Add slack notifications

---

Doppler.BillingUser/Controllers/BillingController.cs

Add a successful message in slack when agreement is created

feat: [DAT-722] dd slack notification successful

---

Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Infrastructure/UserRepository.cs
Doppler.BillingUser/Model/AgreementInformation.cs
Doppler.BillingUser/Model/UserBillingInformation.cs

Here we are updating the origin inbound information in User during the user's purchase

[DAT-729] - Update user origin inbound

---

Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Infrastructure/UserRepository.cs
Doppler.BillingUser/Model/UserBillingInformation.cs

Set the 'UpgradePending' property in false
**Bug:** [DAT-742](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-742)

[DAT-742] - Set the 'UpgradePending' property in false

---

Doppler.BillingUser/appsettings.json

Update sap url to use PROD sap
**Task:** [DAT-761](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-761)

[DAT-761] - Update sap url to use PROD sap

---

Doppler.BillingUser/appsettings.int.json
Doppler.BillingUser/appsettings.qa.json

feat: update configs

---

Doppler.BillingUser/appsettings.json

[NO-TICKET] Update prod setting to use sap test

[NO-TICKET] Update prod setting to use sap test

---

Doppler.BillingUser/appsettings.json

[NO-TICKET] update prod sap url

---

Doppler.BillingUser.Test/PutCurrentPaymentMethodTest.cs
Doppler.BillingUser.Test/PutInvoiceRecipientsTest.cs
Doppler.BillingUser/ExternalServices/Sap/SapHelper.cs
Doppler.BillingUser/ExternalServices/Sap/SapService.cs

Exclude to send to SAP the users with makingsense's domains.
**Task:** [DAT-762](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-762)

[DAT-762] - Exclude to send to SAP the users with makingsense's domains.

---

Doppler.BillingUser.Test/PostAgreementTest.cs
Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Enums/BillingCreditTypeEnum.cs
Doppler.BillingUser/Enums/SourceTypeEnum.cs
Doppler.BillingUser/Infrastructure/BillingRepository.cs
Doppler.BillingUser/Infrastructure/IBillingRepository.cs
Doppler.BillingUser/Utils/SourceTypeHelper.cs

Add monthly plan support to create agreement endpoint

feature: monthly plan support to create agreement

---

Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/ExternalServices/EmailSender/EmailNotificationsConfiguration.cs
Doppler.BillingUser/appsettings.Development.json
Doppler.BillingUser/appsettings.int.json
Doppler.BillingUser/appsettings.json
Doppler.BillingUser/appsettings.qa.json

Integrate with the notification when the user buys a plan by email
**Task:** [DAT-711](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-711)

[DAT-711] - Integrate with the notification when the user buys a plan by email

---

Doppler.BillingUser.Test/PostAgreementTest.cs
Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Infrastructure/BillingRepository.cs
Doppler.BillingUser/Infrastructure/IBillingRepository.cs
Doppler.BillingUser/Model/BillingCreditModel.cs
Doppler.BillingUser/Model/PlanDiscountInformation.cs

Upgrade create agreement endpoint to support contacts monthly plans.

feat: add contacts support to contacts monthly plan agreement

---

Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Infrastructure/IBillingRepository.cs

Send notifications to the user and the admin when the user buys a plan by contacts
**Task:** [DAT-798](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-798)

[DAT-798] - Send notifications to the user and the admin when the user buys a plan by contacts

---

Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Infrastructure/BillingRepository.cs
Doppler.BillingUser/Infrastructure/UserRepository.cs
Doppler.BillingUser/Model/UserBillingInformation.cs
Doppler.BillingUser/appsettings.int.json

Save the correct values in the database for the 'PlanFee' and 'MaxSubscribers' columns.
**Bug:** [DAT-808](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-808)

[DAT-808] - Save the correct values in the database for the 'PlanFee' and 'MaxSubscribers' columns.

---

Doppler.BillingUser/Encryption/EncryptionService.cs

update encryption service
**Task:** No Ticket

[NO-TICKET] - update encryption service

---

Doppler.BillingUser.Test/PostAgreementTest.cs
Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/ExternalServices/EmailSender/EmailNotificationsConfiguration.cs
Doppler.BillingUser/appsettings.Development.json
Doppler.BillingUser/appsettings.int.json
Doppler.BillingUser/appsettings.json
Doppler.BillingUser/appsettings.qa.json

send You've upgraded to a Contacts-based Monthly Plan notification.

feat: send you upgraded to a Contacts-based Monthly Plan notification

---

Dockerfile
Doppler.BillingUser.Test/Doppler.BillingUser.Test.csproj
Doppler.BillingUser/Dockerfile
Doppler.BillingUser/Doppler.BillingUser.csproj

Update solution to use net6
Task: [DAT-810](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-810)

[DAT-810] - Update solution to use net6

---

Doppler.BillingUser.Test/BillingControllerTest.cs
Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/ExternalServices/EmailSender/EmailNotificationsConfiguration.cs
Doppler.BillingUser/appsettings.Development.json
Doppler.BillingUser/appsettings.int.json
Doppler.BillingUser/appsettings.json
Doppler.BillingUser/appsettings.qa.json

Migrate notification for activated stand by subscribers from doppler to new billing api

chore: add notification for activated standby subscribers

---

Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Model/Promotion.cs

Fix issue when the user buys a plan by emails
Bug: [DAT-822](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-822)

[DAT-822] - Fix issue when the user buys a plan by emails

---

Doppler.BillingUser/Doppler.BillingUser.csproj

Remove unused dependency: Serilog.Exceptions

[No-Ticket] remove unused dependency

---

Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Infrastructure/BillingRepository.cs
Doppler.BillingUser/Model/BillingCredit.cs

fix issue when send invoice to sap when the buy is by contacts
**Bug:** [DAT-845](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-845)

[DAT-845] - fix issue when send invoice to sap when the buy is by contacts

---

Doppler.BillingUser/Controllers/BillingController.cs

Remove duplicated code
**Task:** [DAT-848](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-848)

[DAT-848] - Remove duplicated code

---

Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/ExternalServices/EmailSender/EmailNotificationsConfiguration.cs
Doppler.BillingUser/Infrastructure/BillingRepository.cs
Doppler.BillingUser/Services/EmailTemplatesService.cs
Doppler.BillingUser/Services/IEmailTemplatesService.cs
Doppler.BillingUser/appsettings.int.json
Doppler.BillingUser/appsettings.json
Doppler.BillingUser/appsettings.qa.json

Send notifications when the buy is by emails or contacts
Task: [DAT-862](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-862)

[DAT-862] - Send notifications when the buy is by emails or contacts

---

Doppler.BillingUser/appsettings.qa.json

fix: update qa config

---

Doppler.BillingUser.Test/GetCurrentPaymentMethodTest.cs
Doppler.BillingUser.Test/PutCurrentPaymentMethodTest.cs
Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Enums/PaymentWayEnum.cs
Doppler.BillingUser/Infrastructure/BillingRepository.cs
Doppler.BillingUser/Infrastructure/IBillingRepository.cs
Doppler.BillingUser/Infrastructure/UserRepository.cs
Doppler.BillingUser/Model/PaymentMethod.cs
Doppler.BillingUser/Model/User.cs

Update the save of the payment method to integrate with Mexico transfer.
Task: [DAT-619](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-619)

[DAT-619] - Update the save of the payment method to integrate with Mexico transfer

---

Doppler.BillingUser/Infrastructure/BillingRepository.cs

[no-ticket] fix issue with bank fields

---

Doppler.BillingUser.Test/PostAgreementTest.cs
Doppler.BillingUser.Test/PutCurrentPaymentMethodTest.cs
Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Infrastructure/BillingRepository.cs
Doppler.BillingUser/Infrastructure/UserRepository.cs
Doppler.BillingUser/Model/CreateAgreement.cs
Doppler.BillingUser/appsettings.Development.json

Integrate Mexico transfer in the purchase
**Task:** [DAT-606](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-606)

[DAT-606] - Integrate Mexico transfer in the purchase

---

Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Utils/BillingHelper.cs

refactor billing controller

---

Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/ExternalServices/Zoho/IZohoService.cs
Doppler.BillingUser/ExternalServices/Zoho/ZohoService.cs

fix: await RefreshToken response

---

Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Enums/UserTypeEnum.cs
Doppler.BillingUser/Extensions/EnumExtension.cs

Change logic to send the plan type to Zoho
Task: [DAT-881](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-881)

[DAT-881] - Change logic to send the plan type to Zoho

---

Doppler.BillingUser/Controllers/BillingController.cs

Send the payment method of the user and only send the payment dates if not upgrade pending
Task: [DAT-880](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-880)

[DAT-880] - Send the payment method of the user and only send the payment dates if not upgrade pending

---

Doppler.BillingUser/Infrastructure/BillingRepository.cs

Add new fields (Mexico transfer) in the get current payment method endpoint
**Task:** [DAT-883](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-883)

[DAT-883] - Add new fields in the get current payment method endpoint

---

Doppler.BillingUser/Controllers/BillingController.cs

fix issue with Email Movements

[No-ticket] fix issue with Email Movements

---

Doppler.BillingUser/Infrastructure/BillingRepository.cs

Integrate the argentina transfer in the payment method section
**Task:** [DAT-900](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-900)

[DAT-900] - Integrate the argentina transfer in the payment method section

---

Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Infrastructure/BillingRepository.cs
Doppler.BillingUser/Model/BillingCredit.cs
Doppler.BillingUser/Utils/BillingHelper.cs

Integrate the argentina transfer for the buy of plan
Task: [DAT-604](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-604)

[DAT-604] - Integrate the argentina transfer for the buy of plan

---

Doppler.BillingUser.Test/PutBillingControllerTest.cs
Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Infrastructure/BillingRepository.cs
Doppler.BillingUser/Infrastructure/IBillingRepository.cs

Update payment method when the user has transfer and change the country
Task: [DAT-910](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-910)

[DAT-910] - Update payment method when the user has transfer and change the country

---

Doppler.BillingUser/Controllers/BillingController.cs

[No-ticket] - Add authorize filter

---

Doppler.BillingUser.Test/PutCurrentPaymentMethodTest.cs
Doppler.BillingUser/Infrastructure/BillingRepository.cs

Integrate Mercadopago with the payment method section
**Task:** [DAT-607](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-607)

[DAT-607] - Integrate Mercadopago with the payment method section

---

Doppler.BillingUser.Test/Infrastructure/CurrencyRepositoryTest.cs
Doppler.BillingUser/Infrastructure/CurrencyRepository.cs
Doppler.BillingUser/Infrastructure/ICurrencyRepository.cs
Doppler.BillingUser/Model/CurrencyRate.cs
Doppler.BillingUser/Startup.cs

Create a Currency repository. This repository will be used to retrive the Currency rate.
**Task:** [DAT-608](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-608)

[DAT-608] - Create Currency repository

---

Doppler.BillingUser.Test/PostAgreementTest.cs
Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Enums/PaymentStatusEnum.cs
Doppler.BillingUser/Infrastructure/BillingRepository.cs
Doppler.BillingUser/Infrastructure/IBillingRepository.cs
Doppler.BillingUser/Mappers/AccountingEntryForCreditCardMapper.cs
Doppler.BillingUser/Mappers/IAccountingEntryMapper.cs
Doppler.BillingUser/Model/AccountingEntry.cs
Doppler.BillingUser/Model/CreditCardPayment.cs

Add mapper to create the AccountingEntry and create a method to create CreditCardPayment
**Task:** [DAT-608](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-608)

[DAT-608] - Add mapper to create the AccountingEntry

---

Doppler.BillingUser.Test/BillingControllerTest.cs
Doppler.BillingUser.Test/PostAgreementTest.cs
Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Infrastructure/BillingRepository.cs
Doppler.BillingUser/Infrastructure/IBillingRepository.cs
Doppler.BillingUser/Mappers/BillingCredit/BillingCreditForCreditCardMapper.cs
Doppler.BillingUser/Mappers/BillingCredit/BillingCreditForTransferMapper.cs
Doppler.BillingUser/Mappers/BillingCredit/IBillingCreditMapper.cs
Doppler.BillingUser/Model/BillingCreditAgreement.cs

Create mapper to BillingCredit

[DAT-608] - Create mapper to BillingCredit

---

Doppler.BillingUser/Mappers/BillingCredit/BillingCreditForCreditCardMapper.cs
Doppler.BillingUser/Mappers/BillingCredit/BillingCreditForTransferMapper.cs

Fix issue when the user apply a promocode
**Task:** [DAT-928](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-928)

[DAT-928] - Fix issue when the user apply a promocode

---

Doppler.BillingUser/Controllers/BillingController.cs

Not send to sap the sale order when the payment is not approved
**Task:** No ticket

[No-Ticket] - not send to sap the sale order when the payment is not approved

---

Doppler.BillingUser/Infrastructure/UserRepository.cs

fix issue with upgrade pending in null

[No-Ticket] - fix issue with upgrade pending in null

---

Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Infrastructure/IUserRepository.cs
Doppler.BillingUser/Infrastructure/UserRepository.cs

Add new endpoint to update the "LastPurchaseIntentionDate" in User table.

[DOI-581] Add purchase intention endpoint

---

Doppler.BillingUser/Infrastructure/BillingRepository.cs
Doppler.BillingUser/Infrastructure/IBillingRepository.cs

The code of this pr is a part of [this flow](https://mermaid.live/edit#pako:eNqVU8tuwjAQ_BXLJyqBcs8BqYSq4tASlXLzZWsv1Gpiu2ZdCSH-vTZJpSY8FHJKPLMz483ugUurkOdcmB1-BzQS5xq2HmphBDnwpKV2YIi9oJegbAlbewN6LBd9dKarSpvteof-NjqfJfCfGJtMp73ynJXL1TsTPFPWuQr95KPBJyESsoUhjOFJW5MdQEobDBmo8Zi1si7KvlrSGy1PLMGTZ9cjunZvlLNnJOZgX6MhYVh8uoRuRY_eudIF7bIhMm02tsdupM860Cs4S9_paZNGmx-rJbJRi72hsw-94vnsgtmiLRxqtnYKCAf5XQ1beFSaCvCKjdL54LBFMThn9Eg52790f19WBBR21-0687D8auhF2rUxr9HXoFXcukOaJsHpE2sUPI-vCjcQKkpzeYzUcGrnU2yH9TwnH3DMIZBd7Y38-2447do2h8dfdthjKA) 
Other pull requests that are part of the flow:
- [Add GetInvoice method](https://github.com/FromDoppler/doppler-billing-user/pull/176)
- [Add CreatePayment method](https://github.com/FromDoppler/doppler-billing-user/pull/177)
Added a method to update the invoice status

[DAT-951] - Create method UpdateInvoiceStatus

---

Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/ExternalServices/FirstData/PaymentGateway.cs

Retrieve the first data's error to show in the payment method section
**Task:** [DAT-572](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-572)

[DAT-572] - Retrieve the first data's error to show in the payment method section

---

Doppler.BillingUser/Infrastructure/BillingRepository.cs
Doppler.BillingUser/Infrastructure/IBillingRepository.cs
Doppler.BillingUser/Mappers/AccountingEntry/AccountingEntryForCreditCardMapper.cs
Doppler.BillingUser/Mappers/AccountingEntry/AccountingEntryForMercadopagoMapper.cs
Doppler.BillingUser/Model/AccountingEntry.cs

Status property from AccountingEntryModel was changed from string to enum.

[No-Ticket] -  Refactor BillingController

---

Doppler.BillingUser/Controllers/BillingController.cs

Comment line to call account plan api from billing user api

[No-Ticket] Comment lin to call account plan api from billing user api

---

Doppler.BillingUser/Controllers/BillingController.cs

Set the authorization number to send to SAP

[No-Ticket] - Set the authorization number to send to SAP

---

Doppler.BillingUser.Test/MercadoPagoServiceTest.cs
Doppler.BillingUser.Test/PostMercadoPagoNotificationTest.cs
Doppler.BillingUser/Controllers/WebhooksController.cs
Doppler.BillingUser/Enums/MercadoPagoPaymentStatusEnum.cs
Doppler.BillingUser/Enums/PaymentStatusEnum.cs
Doppler.BillingUser/ExternalServices/MercadoPagoApi/MercadoPagoNotification.cs
Doppler.BillingUser/ExternalServices/MercadoPagoApi/MercadoPagoPayment.cs
Doppler.BillingUser/Infrastructure/BillingRepository.cs
Doppler.BillingUser/Mappers/AccountingEntry/AccountingEntryForMercadopagoMapper.cs
Doppler.BillingUser/Mappers/PaymentStatus/IPaymentStatusMapper.cs
Doppler.BillingUser/Mappers/PaymentStatus/PaymentStatusMapper.cs
Doppler.BillingUser/Model/AccountingEntry.cs
Doppler.BillingUser/Startup.cs

When a customer makes a payment through Mercado Pago, payment status could be resolved at the moment or could be Pending.
In order to handle this situation, MercadoPago sends webhook notifications with the payment updates. So we need to create an endpoint to receive that notifications and update payment status.
To clarify the complete flow of the operation, we present the following diagram:
```mermaid
sequenceDiagram
participant MercadoPagoWebHook
participant MercadoPago
participant MercadoPagoAPI
participant BillingUserAPI
participant BillingUserDB
MercadoPagoWebHook ->>+ BillingUserAPI: POST "/doppler-billing-user/Integration/accounts/{accountname}/MercadopagoNotification"
activate MercadoPagoWebHook
BillingUserAPI->>+MercadoPagoAPI: Get payment
MercadoPagoAPI->>+MercadoPago: Get …
```

[DAT-945] - Create MercadoPago notifications endpoint

---

Doppler.BillingUser/Controllers/WebhooksController.cs

This PR applies changes suggested by @afantini in https://github.com/FromDoppler/doppler-billing-user/pull/181

[No-Ticket] - Refactor webhookcontroller

---

Doppler.BillingUser/Controllers/WebhooksController.cs
Doppler.BillingUser/ExternalServices/EmailSender/EmailNotificationsConfiguration.cs
Doppler.BillingUser/Services/EmailTemplatesService.cs
Doppler.BillingUser/Services/IEmailTemplatesService.cs
Doppler.BillingUser/appsettings.Development.json
Doppler.BillingUser/appsettings.int.json
Doppler.BillingUser/appsettings.json
Doppler.BillingUser/appsettings.qa.json

Send an email when any mercadopago's payment was approved
**Task:** [DAT-962](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-962)

[DAT-962] - Send an email when any mercadopago payment was approved

---

Doppler.BillingUser/Infrastructure/BillingRepository.cs

We need to add some missing fields when create a payment with MercadoPago.
Fields:
- IdCurrencyType
- CurrencyRate
- Taxes

[DAT-974] - Add payment missing fields

---

Doppler.BillingUser.Test/MercadoPagoServiceTest.cs
Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/ExternalServices/EmailSender/EmailNotificationsConfiguration.cs
Doppler.BillingUser/ExternalServices/FirstData/PaymentGateway.cs
Doppler.BillingUser/ExternalServices/MercadoPagoApi/IMercadoPagoService.cs
Doppler.BillingUser/ExternalServices/MercadoPagoApi/MercadoPagoService.cs
Doppler.BillingUser/Services/EmailTemplatesService.cs
Doppler.BillingUser/Services/IEmailTemplatesService.cs
Doppler.BillingUser/appsettings.Development.json
Doppler.BillingUser/appsettings.int.json
Doppler.BillingUser/appsettings.json
Doppler.BillingUser/appsettings.qa.json

Send notification when the mercadopago payment fail
**Task:** [DAT-961](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-961)

[DAT-961] - Send notification when the mercadopago payment fail

---

Doppler.BillingUser/ExternalServices/EmailSender/EmailNotificationsConfiguration.cs
Doppler.BillingUser/ExternalServices/MercadoPagoApi/MercadoPagoService.cs
Doppler.BillingUser/Services/EmailTemplatesService.cs
Doppler.BillingUser/Services/IEmailTemplatesService.cs
Doppler.BillingUser/appsettings.Development.json
Doppler.BillingUser/appsettings.int.json
Doppler.BillingUser/appsettings.json
Doppler.BillingUser/appsettings.qa.json

Send notification when the mercadopago paymen is in process
**Task:** [DAT-963](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-963)

[DAT-963] - Send notification when the mercadopago paymen is in process

---

Doppler.BillingUser.Test/MercadoPagoServiceTest.cs
Doppler.BillingUser/ExternalServices/MercadoPagoApi/MercadoPagoService.cs

Fix issue with expiration year

[No-Ticket] - Fix issue with expiration year

---

Doppler.BillingUser.Test/PostAgreementTest.cs
Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Enums/BillingCreditTypeEnum.cs
Doppler.BillingUser/ExternalServices/EmailSender/EmailNotificationsConfiguration.cs
Doppler.BillingUser/Infrastructure/BillingRepository.cs
Doppler.BillingUser/Infrastructure/IBillingRepository.cs
Doppler.BillingUser/Infrastructure/IPromotionRepository.cs
Doppler.BillingUser/Infrastructure/IUserRepository.cs
Doppler.BillingUser/Infrastructure/PromotionRepository.cs
Doppler.BillingUser/Infrastructure/UserRepository.cs
Doppler.BillingUser/Mappers/BillingCredit/BillingCreditForCreditCardMapper.cs
Doppler.BillingUser/Mappers/BillingCredit/BillingCreditForMercadopagoMapper.cs
Doppler.BillingUser/Mappers/BillingCredit/BillingCreditForTransferMapper.cs
Doppler.BillingUser/Mappers/BillingCredit/IBillingCreditMapper.cs
Doppler.BillingUser/Model/BillingCredit.cs
Doppler.BillingUser/Model/BillingCreditModel.cs
Doppler.BillingUser/Model/Promotion.cs
Doppler.BillingUser/Services/EmailTemplatesService.cs
Doppler.BillingUser/Services/IEmailTemplatesService.cs
Doppler.BillingUser/Utils/BillingHelper.cs
Doppler.BillingUser/appsettings.Development.json
Doppler.BillingUser/appsettings.int.json
Doppler.BillingUser/appsettings.json
Doppler.BillingUser/appsettings.qa.json

Integrate upgrade between monthly plans
**Task:** [DAT-983](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-983)

[DAT-983] - Integrate upgrade between monthly plans

---

Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Infrastructure/UserRepository.cs
Doppler.BillingUser/Model/UserTypePlanInformation.cs
Doppler.BillingUser/Services/EmailTemplatesService.cs
Doppler.BillingUser/Services/IEmailTemplatesService.cs

Update template for the UpdatePlan notification
Task: [DAT-1006](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1006)

[DAT-1006] - Update template for the UpdatePlan notification

---

Doppler.BillingUser/Controllers/BillingController.cs

Fix issue when send the amount to MP. 
We changed the logic to calculate amount to send to MP

[No-Ticket] - fix calculate amount to send MP

---

Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Infrastructure/IPromotionRepository.cs
Doppler.BillingUser/Infrastructure/PromotionRepository.cs
Doppler.BillingUser/Model/TimesApplyedPromocode.cs

Update the query to get how many times some promocode was applied
**Task:** [DAT-1017](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1017)

[DAT-1017] - Update the query to get how many times somepromocode was applied

---

Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/ExternalServices/AccountPlansApi/AccountPlansService.cs
Doppler.BillingUser/ExternalServices/AccountPlansApi/IAccountPlansService.cs
Doppler.BillingUser/Infrastructure/BillingRepository.cs
Doppler.BillingUser/Model/DiscountPlanFeeAdmin.cs
Doppler.BillingUser/Model/DiscountPrepayment.cs
Doppler.BillingUser/Model/DiscountPromocode.cs
Doppler.BillingUser/Model/PlanAmountDetails.cs
Doppler.BillingUser/Services/EmailTemplatesService.cs
Doppler.BillingUser/Services/IEmailTemplatesService.cs

Include amout details in the update plan notification
**Task:** [DAT-1048](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1048)

[DAT-1048] - Include amout details in the update plan notification

---

Doppler.BillingUser.Test/PaymentAmountHelperTest.cs
Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Controllers/WebhooksController.cs
Doppler.BillingUser/Mappers/AccountingEntry/AccountingEntryForMercadopagoMapper.cs
Doppler.BillingUser/Mappers/BillingCredit/BillingCreditForMercadopagoMapper.cs
Doppler.BillingUser/Model/PaymentAmountDetail.cs
Doppler.BillingUser/Services/IPaymentAmountHelper.cs
Doppler.BillingUser/Services/PaymentAmounthelper.cs
Doppler.BillingUser/Startup.cs

Jira Ticket: [DAT-1010](https://makingsense.atlassian.net/browse/DAT-1010)

[DAT-1010] - Extract payment amount details

---

Doppler.BillingUser/Services/EmailTemplatesService.cs

Jira Ticket: [DAT-1052](https://makingsense.atlassian.net/browse/DAT-1052)

[DAT-1052] - Change 'from' address in emails for plan upgrades

---

Doppler.BillingUser.Test/PostAgreementTest.cs
Doppler.BillingUser/Controllers/BillingController.cs

Jira ticket: [DAT-1026](https://makingsense.atlassian.net/browse/DAT-1026)

[DAT-1026] - fix: activate standby subscribers for 'by emails' and 'by credits' plans

---

Doppler.BillingUser.Test/PostAgreementTest.cs
Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Enums/BillingCreditTypeEnum.cs
Doppler.BillingUser/Infrastructure/BillingRepository.cs
Doppler.BillingUser/Model/BillingCredit.cs
Doppler.BillingUser/Services/EmailTemplatesService.cs

Integrate update between contacts plans
**Task:** [](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-984)

[DAT-984] - Integrate update between contacts plans

---

Doppler.BillingUser/Controllers/BillingController.cs

No actualizar cantidad de suscriptores en cuenta hasta que no se apruebe el upgrade
**Task:** [DAT-1075](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1075)
**Screenshots:**
**Contacts:**
**Before:**
**After:**
**Emails:**
**Before:**
**After:**
**Credits:**
**Before:**
**After:**

[DAT-1075] - No actualizar cantidad de suscriptores en cuenta hasta que no se apruebe el upgrade

---

Doppler.BillingUser.Test/PaymentAmountHelperTest.cs
Doppler.BillingUser/Services/PaymentAmounthelper.cs

Fix issue with transaction amount when send this to mercado pago

[No-Ticket] - fix issue with transaction amount when send this to mercado pago

---

Doppler.BillingUser/ExternalServices/Sap/SapBillingDto.cs
Doppler.BillingUser/Utils/BillingHelper.cs

Update free text when the user has an update plan
**Task:** [DAT-1043](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1043)

[DAT-1043] -Update free text when the user has an update plan

---

Doppler.BillingUser/Services/EmailTemplatesService.cs

Include billing account in all the transactional email and also include the dopplerapps account in the replyTo.
**Task:** [DAT-1102](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1102)

[DAT-1102] -Include billing account in all the transactional email and also include the dopplerapps account in the replyTo.

---

Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Mappers/BillingCredit/BillingCreditForCreditCardMapper.cs
Doppler.BillingUser/Mappers/BillingCredit/BillingCreditForMercadopagoMapper.cs
Doppler.BillingUser/Mappers/BillingCredit/BillingCreditForTransferMapper.cs
Doppler.BillingUser/Mappers/BillingCredit/IBillingCreditMapper.cs

Fix issue: Reset the current month when the user does update plan.
Bug: [DAT-1106](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1106)

[DAT-1106] - reset the current month when the user does update plan

---

Doppler.BillingUser.Test/BillingControllerTest.cs
Doppler.BillingUser.Test/MercadoPagoServiceTest.cs
Doppler.BillingUser.Test/PostAgreementTest.cs
Doppler.BillingUser.Test/PutCurrentPaymentMethodTest.cs
Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/ExternalServices/EmailSender/EmailNotificationsConfiguration.cs
Doppler.BillingUser/ExternalServices/FirstData/IPaymentGateway.cs
Doppler.BillingUser/ExternalServices/FirstData/PaymentGateway.cs
Doppler.BillingUser/ExternalServices/MercadoPagoApi/IMercadoPagoService.cs
Doppler.BillingUser/ExternalServices/MercadoPagoApi/MercadoPagoService.cs
Doppler.BillingUser/Infrastructure/BillingRepository.cs
Doppler.BillingUser/Services/EmailTemplatesService.cs
Doppler.BillingUser/Services/IEmailTemplatesService.cs
Doppler.BillingUser/appsettings.Development.json
Doppler.BillingUser/appsettings.int.json
Doppler.BillingUser/appsettings.json
Doppler.BillingUser/appsettings.qa.json

Add new transactional emails from checkout.
**Task:** [DAT-934](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-934)

[DAT-934] - Add new transactional emails from checkout

---

Doppler.BillingUser/Controllers/BillingController.cs

Not set upgradepending equal 1 to by credits.

[No-Ticket] - Not set upgradepending equal 1 to by credits

---

Doppler.BillingUser/Controllers/BillingController.cs

Fix issue when the user does to downgrade
Task: [DAT-1130](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1130)

[DAT-1130] - Fix issue when the user does to downgrade

---

Doppler.BillingUser/Infrastructure/BillingRepository.cs
Doppler.BillingUser/Mappers/BillingCredit/BillingCreditForCreditCardMapper.cs
Doppler.BillingUser/Mappers/BillingCredit/BillingCreditForMercadopagoMapper.cs
Doppler.BillingUser/Mappers/BillingCredit/BillingCreditForTransferMapper.cs
Doppler.BillingUser/Model/BillingCreditAgreement.cs

Insert the PromotionDuration in the BillingRequest.
**Task:** [DAT-1136](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1136)

[DAT-1136] - Insert the PromotionDuration in the BillingRequest

---

Doppler.BillingUser/Infrastructure/BillingRepository.cs

[DAT-1136] Fix issue in the insert query

---

Doppler.BillingUser/Controllers/BillingController.cs

Update message to only supports upselling
Task: [DAT-1127](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1127)

[DAT-1127] - Update message to only supports upselling

---

Doppler.BillingUser/Controllers/BillingController.cs

Remove set the UTCUpgrade when the user buys credits.
**Task:** [DAT-1177](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1177)

[DAT-1177] - Remove set the UTCUpgrade when the user buys credits

---

Doppler.BillingUser/Controllers/BillingController.cs

Fix issue when the user buys credits
Bug: [DAT-1182](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1182)

[DAT-1182] - Fix issue when the user buys credits

---

Doppler.BillingUser.Test/BillingControllerTest.cs
Doppler.BillingUser.Test/PostAgreementTest.cs
Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Enums/PaymentStatusEnum.cs
Doppler.BillingUser/Infrastructure/IUserPaymentHistoryRepository.cs
Doppler.BillingUser/Infrastructure/UserPaymentHistoryRepository.cs
Doppler.BillingUser/Model/UserPaymentHistory.cs
Doppler.BillingUser/Startup.cs

Insert a new record in the UserPaymentHistory when the user buys a plan.
**Task:** [DAT-1181](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1181)

[DAT-1181] -Insert a new record in the UserPaymentHistory when the user buys a plan

---

Doppler.BillingUser.Test/PostMercadoPagoNotificationTest.cs
Doppler.BillingUser/Controllers/WebhooksController.cs
Doppler.BillingUser/Infrastructure/BillingRepository.cs
Doppler.BillingUser/Infrastructure/IBillingRepository.cs

Save the ErrorMessage when mercado pago decline the payment.
Bug: [DAT-1204](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1204)

[DAT-1204] - Save the error message when mercado pago decline the payment

---

Doppler.BillingUser/Controllers/BillingController.cs

Save the ErrorMessage when the payment throws an exception.
**Task:** [DAT-1205](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1205)

[DAT-1205] - Save the ErrorMessage when the payment throws an exception

---

Doppler.BillingUser.Test/GetCurrentPaymentMethodTest.cs
Doppler.BillingUser.Test/PutCurrentPaymentMethodTest.cs
Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/DopplerSecurity/DopplerAuthorizationRequirement.cs
Doppler.BillingUser/DopplerSecurity/DopplerSecurityDefaults.cs
Doppler.BillingUser/DopplerSecurity/DopplerSecurityServiceCollectionExtensions.cs
Doppler.BillingUser/DopplerSecurity/IsProvisoryUserAuthorizationHandler.cs
Doppler.BillingUser/DopplerSecurity/Policies.cs

Jira Ticket: [DAT-1237](https://makingsense.atlassian.net/browse/DAT-1237)
Create a new security policy for provisory users

feat: add provisory user security policy

---

Doppler.BillingUser/Mappers/BillingCredit/BillingCreditForCreditCardMapper.cs
Doppler.BillingUser/Mappers/BillingCredit/BillingCreditForMercadopagoMapper.cs
Doppler.BillingUser/Mappers/BillingCredit/BillingCreditForTransferMapper.cs

Set 1 in the discountId by default

[No-ticket] Set 1 in the discountId

---

Doppler.BillingUser.Test/GetDeclinedInvoicesTest.cs
Doppler.BillingUser.Test/ReprocessTest.cs
Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Infrastructure/BillingRepository.cs
Doppler.BillingUser/Infrastructure/IBillingRepository.cs
Doppler.BillingUser/Model/DeclinedInvoiceData.cs
Doppler.BillingUser/Model/FailedToReprocessInvoice.cs
Doppler.BillingUser/Model/GetDeclinedInvoicesResult.cs
Doppler.BillingUser/Model/ReprocessInvoicePaymentResult.cs
Doppler.BillingUser/Model/ReprocessInvoiceResult.cs

Add new endpoint to get the declined invoices of a user and the total amount of debt the user has.
[DAT-1245](https://makingsense.atlassian.net/browse/DAT-1254)

Dat 1254 get declined invoices endpoint

---

Doppler.BillingUser/Controllers/BillingController.cs

Add validation so the api doesn't break when user is null
Jira ticket [DAT-1254](https://makingsense.atlassian.net/browse/DAT-1254)

fix: add validation for when user is null in get declined invoices

---

Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/ExternalServices/EmailSender/EmailNotificationsConfiguration.cs
Doppler.BillingUser/Infrastructure/BillingRepository.cs
Doppler.BillingUser/Model/AccountingEntry.cs
Doppler.BillingUser/Model/DeclinedInvoiceData.cs
Doppler.BillingUser/Model/FailedToReprocessInvoice.cs
Doppler.BillingUser/Model/ReprocessInvoiceResult.cs
Doppler.BillingUser/Services/EmailTemplatesService.cs
Doppler.BillingUser/Services/IEmailTemplatesService.cs
Doppler.BillingUser/appsettings.int.json
Doppler.BillingUser/appsettings.qa.json

[DAT-1256](https://makingsense.atlassian.net/browse/DAT-1256)
Add email sending to the reprocess endpoint to inform the finance team when a user has reprocessed pending invoices

feat: send notification email to the finance team

---

Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Model/ReprocessInvoicePaymentResult.cs

[DAT-1267](https://makingsense.atlassian.net/browse/DAT-1267)
Add Logic to reprocess pending invoices in the reprocess endpoint

feat: add pending invoices logic to reprocess endpoint

---

Doppler.BillingUser.Test/PaymentStatusMapperTest.cs
Doppler.BillingUser/ApiModels/DeclinedInvoiceData.cs
Doppler.BillingUser/ApiModels/GetDeclinedInvoicesResult.cs
Doppler.BillingUser/ApiModels/PaymentStatusApiEnum.cs
Doppler.BillingUser/ApiModels/ReprocessInvoicePaymentResult.cs
Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Enums/ReprocessInvoicePaymentResultEnum.cs
Doppler.BillingUser/Mappers/PaymentStatus/IPaymentStatusMapper.cs
Doppler.BillingUser/Mappers/PaymentStatus/PaymentStatusMapper.cs

create ApiModels folder and separate in and out models

fix: create ApiModels folder and separate in and out models

---

Doppler.BillingUser.Test/BillingControllerTest.cs
Doppler.BillingUser.Test/MercadoPagoServiceTest.cs
Doppler.BillingUser.Test/PostAgreementTest.cs
Doppler.BillingUser.Test/ReprocessTest.cs
Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/ExternalServices/FirstData/IPaymentGateway.cs
Doppler.BillingUser/ExternalServices/FirstData/PaymentGateway.cs
Doppler.BillingUser/ExternalServices/MercadoPagoApi/IMercadoPagoService.cs
Doppler.BillingUser/ExternalServices/MercadoPagoApi/MercadoPagoService.cs
Doppler.BillingUser/Mappers/PaymentStatus/PaymentStatusMapper.cs

[DAT-1272](https://makingsense.atlassian.net/browse/DAT-12720)
Limit the sending of emails so that they are not sent when they were called by the reprocess endpoint

fix: limit the sending of emails for the reprocess endpoint

---

Dockerfile
Doppler.BillingUser.Test/Doppler.BillingUser.Test.csproj
Doppler.BillingUser/Dockerfile
Doppler.BillingUser/Doppler.BillingUser.csproj

fix: reset dependencies

---

Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Infrastructure/IUserPaymentHistoryRepository.cs
Doppler.BillingUser/Infrastructure/IUserRepository.cs
Doppler.BillingUser/Infrastructure/UserPaymentHistoryRepository.cs
Doppler.BillingUser/Infrastructure/UserRepository.cs
Doppler.BillingUser/Settings/AttemptsToUpdateSettings.cs
Doppler.BillingUser/Startup.cs
Doppler.BillingUser/appsettings.json

Cancel user when it has more than 10 failed attempts.
**Task:** [DAT-1270](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1270)

[DAT-1270] - Cancel user when it has more than 10 failed attempts

---

Dockerfile
Doppler.BillingUser.Test/Doppler.BillingUser.Test.csproj
Doppler.BillingUser/Dockerfile
Doppler.BillingUser/Doppler.BillingUser.csproj

update dependencies that dont require .NET 7

fix: update depencies

---

Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Settings/AttemptsToUpdateSettings.cs
Doppler.BillingUser/appsettings.int.json
Doppler.BillingUser/appsettings.json
Doppler.BillingUser/appsettings.qa.json

[DAT-1270] Add new settings

---

Dockerfile
Doppler.BillingUser.Test/Doppler.BillingUser.Test.csproj
Doppler.BillingUser/Dockerfile
Doppler.BillingUser/Doppler.BillingUser.csproj

Fix dependencies

---

Doppler.BillingUser/ApiModels/ReprocessByTransferUserData.cs
Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/ExternalServices/EmailSender/EmailNotificationsConfiguration.cs
Doppler.BillingUser/Services/EmailTemplatesService.cs
Doppler.BillingUser/Services/IEmailTemplatesService.cs
Doppler.BillingUser/appsettings.int.json

add endpoint to send email to finance when user request a reprocess by transfer.
[DAT-1274](https://makingsense.atlassian.net/browse/DAT-1274)

feat: add endpoint to send email to finance when user request a reprocess

---

Doppler.BillingUser.Test/PutCurrentPaymentMethodTest.cs
Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Infrastructure/BillingRepository.cs
Doppler.BillingUser/Infrastructure/IBillingRepository.cs
Doppler.BillingUser/Model/BillingCreditPaymentInfo.cs

update billing credit when payment method is updated

fix: update billing credit when payment method is updated

---

Dockerfile
Doppler.BillingUser.Test/Doppler.BillingUser.Test.csproj
Doppler.BillingUser/Dockerfile
Doppler.BillingUser/Doppler.BillingUser.csproj

fix: update dependencies

---

Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Infrastructure/IUserRepository.cs
Doppler.BillingUser/Infrastructure/UserPaymentHistoryRepository.cs
Doppler.BillingUser/Infrastructure/UserRepository.cs
Doppler.BillingUser/Model/UserPaymentHistory.cs
Doppler.BillingUser/appsettings.int.json
Doppler.BillingUser/appsettings.json
Doppler.BillingUser/appsettings.qa.json

Add comments when the user is automatically canceled and change frequency to cancel user.
Task: [DAT-1296](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1296)

[DAT-1296] - Add comments when the user is automatically canceled and change frequency to cancel user

---

Doppler.BillingUser/Controllers/BillingController.cs

Fix bug payment method was not being updated when the selected method was transfer

fix: bug update payment method failed for transfer

---

Doppler.BillingUser/ApiModels/PaymentStatusApiEnum.cs
Doppler.BillingUser/Enums/PaymentStatusEnum.cs
Doppler.BillingUser/Mappers/PaymentStatus/PaymentStatusMapper.cs

Include failed status when get the invoices
**Task:** [DAT-1349](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1349)
[DAT-1349]: https://makingsense.atlassian.net/browse/DAT-1349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-1349] - Include failed status when get the invoices

---

Doppler.BillingUser/Controllers/BillingController.cs

Log message in slack channel when invoice was not send to SAP

fix: log error could not send invoice to sap

---

Doppler.BillingUser.Test/PostAgreementTest.cs
Doppler.BillingUser.Test/PostMercadoPagoNotificationTest.cs
Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Controllers/WebhooksController.cs
Doppler.BillingUser/Enums/BillingCreditTypeEnum.cs
Doppler.BillingUser/ExternalServices/EmailSender/EmailNotificationsConfiguration.cs
Doppler.BillingUser/Infrastructure/BillingRepository.cs
Doppler.BillingUser/Infrastructure/IBillingRepository.cs
Doppler.BillingUser/Infrastructure/IPromotionRepository.cs
Doppler.BillingUser/Infrastructure/PromotionRepository.cs
Doppler.BillingUser/Infrastructure/UserRepository.cs
Doppler.BillingUser/Model/BillingCredit.cs
Doppler.BillingUser/Model/UserBillingInformation.cs
Doppler.BillingUser/Services/EmailTemplatesService.cs
Doppler.BillingUser/Services/IEmailTemplatesService.cs
Doppler.BillingUser/appsettings.Development.json
Doppler.BillingUser/appsettings.int.json
Doppler.BillingUser/appsettings.json
Doppler.BillingUser/appsettings.qa.json

Approve billing request or cancel when the MercadoPago payment was approved or declined
Task: [DAT-1175](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1175)
[DAT-1175]: https://makingsense.atlassian.net/browse/DAT-1175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-1175] - Approve billing request or cancel when the MercadoPago payment was approved or declined

---

Dockerfile
Doppler.BillingUser.Test/Doppler.BillingUser.Test.csproj
Doppler.BillingUser/Dockerfile
Doppler.BillingUser/Doppler.BillingUser.csproj

[No ticket] Update dependencies

No ticket update dependencies

---

Doppler.BillingUser/Services/EmailTemplatesService.cs

Include comercial email in the rejected email.
**Task:** [DAT-1375](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1375)
[DAT-1375]: https://makingsense.atlassian.net/browse/DAT-1375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-1375] Include comercial email in the rejected email

---

Dockerfile
Doppler.BillingUser/Dockerfile
Doppler.BillingUser/Doppler.BillingUser.csproj

[DAT-1378] - Update dependencies

---

Doppler.BillingUser/Controllers/WebhooksController.cs

Cancel billing request when the Mercadopago payment was rejected and the billing credit status is credits request.
**Task:** [DAT-1396](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1396)
[DAT-1396]: https://makingsense.atlassian.net/browse/DAT-1396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-1396] - Cancel billing request when the Mercadopago payment was rejected and the billing credit status is credits request

---

Doppler.BillingUser/Controllers/WebhooksController.cs

[No-Ticket] - Update logic to send email

---

Doppler.BillingUser/appsettings.Development.json

[DAT-1421](https://makingsense.atlassian.net/browse/DAT-1421)
Change db connection string for development
[DAT-1421]: https://makingsense.atlassian.net/browse/DAT-1421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-1421] - change db connection string

---

Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Enums/BillingCreditTypeEnum.cs
Doppler.BillingUser/ExternalServices/EmailSender/EmailNotificationsConfiguration.cs
Doppler.BillingUser/Infrastructure/BillingRepository.cs
Doppler.BillingUser/Infrastructure/IBillingRepository.cs
Doppler.BillingUser/Mappers/BillingCredit/BillingCreditForCreditCardMapper.cs
Doppler.BillingUser/Model/PlanAmountDetails.cs
Doppler.BillingUser/Services/EmailTemplatesService.cs
Doppler.BillingUser/Services/IEmailTemplatesService.cs
Doppler.BillingUser/Utils/BillingHelper.cs
Doppler.BillingUser/appsettings.Development.json
Doppler.BillingUser/appsettings.int.json
Doppler.BillingUser/appsettings.json
Doppler.BillingUser/appsettings.qa.json

Support change plan current indivual to contacts or emails
**Task:** [DAT-1400](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1400)
[DAT-1400]: https://makingsense.atlassian.net/browse/DAT-1400?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-1400] - Support change plan current indivual to contacts or emails

---

Doppler.BillingUser.Test/GetCurrentPaymentMethodTest.cs
Doppler.BillingUser/Infrastructure/BillingRepository.cs
Doppler.BillingUser/Infrastructure/UserRepository.cs
Doppler.BillingUser/Model/PaymentMethod.cs
Doppler.BillingUser/Model/UserBillingInformation.cs
Doppler.BillingUser/Services/EmailTemplatesService.cs

Jira ticket: https://makingsense.atlassian.net/browse/DAT-1451
- Save parameter TaxRegime in database when updating the payment method and return it when getting the payment method.
- Send the taxRegime parameter when a user creates a new agreement
Evidence
-

Dat 1451 save tax regime

---

Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Mappers/BillingCredit/BillingCreditForCreditCardMapper.cs
Doppler.BillingUser/Mappers/BillingCredit/BillingCreditForMercadopagoMapper.cs
Doppler.BillingUser/Mappers/BillingCredit/BillingCreditForTransferMapper.cs
Doppler.BillingUser/Services/EmailTemplatesService.cs

Update logic to calculate the CurrentMonthPlan
**Task:** [DAT-1471](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1471)
[DAT-1471]: https://makingsense.atlassian.net/browse/DAT-1471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-1471] - Update logic to calculate the CurrentMonthPlan

---

Doppler.BillingUser/Controllers/BillingController.cs

Generate movements when plan change credits to montly

[No-Task] Generate movements when plan change credits to montly

---

Doppler.BillingUser.Test/ExternalServices/CloverServiceTest.cs
Doppler.BillingUser.Test/PostAgreementTest.cs
Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/ExternalServices/Clover/CloverService.cs
Doppler.BillingUser/ExternalServices/Clover/CloverSettings.cs
Doppler.BillingUser/ExternalServices/Clover/Entities/CreditCard.cs
Doppler.BillingUser/ExternalServices/Clover/Entities/CustomerCard.cs
Doppler.BillingUser/ExternalServices/Clover/Entities/CustomerCards.cs
Doppler.BillingUser/ExternalServices/Clover/Errors/ApiError.cs
Doppler.BillingUser/ExternalServices/Clover/ICloverService.cs
Doppler.BillingUser/ExternalServices/Clover/Requests/CustomerRequest.cs
Doppler.BillingUser/ExternalServices/Clover/Requests/PaymentRequest.cs
Doppler.BillingUser/ExternalServices/Clover/Responses/CustomerResponse.cs
Doppler.BillingUser/ExternalServices/FirstData/PaymentGateway.cs
Doppler.BillingUser/ExternalServices/MercadoPagoApi/MercadoPagoService.cs
Doppler.BillingUser/Infrastructure/BillingRepository.cs
Doppler.BillingUser/Services/EmailTemplatesService.cs
Doppler.BillingUser/Services/IEmailTemplatesService.cs
Doppler.BillingUser/Startup.cs
Doppler.BillingUser/appsettings.Development.json
Doppler.BillingUser/appsettings.int.json
Doppler.BillingUser/appsettings.json
Doppler.BillingUser/appsettings.qa.json

Integrate  update payment method and buy a new plan with clover api
Task: [DAT-1571](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1571)
[DAT-1571]: https://makingsense.atlassian.net/browse/DAT-1571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-1571] - Integrate  update payment method and buy a new plan with clover api

---

Doppler.BillingUser.Test/ExternalServices/CloverServiceTest.cs
Doppler.BillingUser/ExternalServices/Clover/CloverService.cs

[No-Ticket] Change exception type

---

Doppler.BillingUser/appsettings.json

Set in true the variable to UseCloverApi
Task: [DAT-1586](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1586)
[DAT-1586]: https://makingsense.atlassian.net/browse/DAT-1586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-1586] - Set in true the variable to UseCloverApi

---

Doppler.BillingUser.Test/GetCurrentPaymentMethodTest.cs
Doppler.BillingUser.Test/PutCurrentPaymentMethodTest.cs
Doppler.BillingUser/ApiModels/GetPaymentMethodResult.cs
Doppler.BillingUser/ApiModels/TaxCertificate.cs
Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/ExternalServices/Aws/AwsS3Service.cs
Doppler.BillingUser/ExternalServices/Aws/IFileStorage.cs
Doppler.BillingUser/Infrastructure/BillingRepository.cs
Doppler.BillingUser/Mappers/PaymentMethod/PaymentMethodMapper.cs
Doppler.BillingUser/Model/PaymentMethod.cs

Use the Amazon S3 service to save the tax Certificate.
Jira Ticket: [DAT-1443](https://makingsense.atlassian.net/browse/DAT-1443)
Evidence
-
[DAT-1443]: https://makingsense.atlassian.net/browse/DAT-1443?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-1443] - save tax certificate

---

Doppler.BillingUser.Test/ExternalServices/CloverServiceTest.cs
Doppler.BillingUser/ExternalServices/Clover/CloverService.cs

Show new message error in the slack channel.
**Task:** [DAT-1594](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1594)
[DAT-1594]: https://makingsense.atlassian.net/browse/DAT-1594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-1594] - Show new message error in the slack channel

---

Doppler.BillingUser.Test/ExternalServices/CloverServiceTest.cs
Doppler.BillingUser/ExternalServices/Clover/CloverService.cs

Add custom error code when the error is insufficient funds.
**Task:** [DAT-1605](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1605)
[DAT-1605]: https://makingsense.atlassian.net/browse/DAT-1605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-1605] - Add custom error code when the error is insufficient funds

---

Doppler.BillingUser.Test/MercadoPagoServiceTest.cs
Doppler.BillingUser/ExternalServices/MercadoPagoApi/Error/ApiError.cs
Doppler.BillingUser/ExternalServices/MercadoPagoApi/MercadoPagoService.cs

Return the Api error when MP throws an exception
Task: [DAT-1615](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1615)
[DAT-1615]: https://makingsense.atlassian.net/browse/DAT-1615?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-1615]- Return the Api error when MP throws an exception

---

Doppler.BillingUser/Mappers/BillingCredit/BillingCreditForCreditCardMapper.cs
Doppler.BillingUser/Mappers/BillingCredit/BillingCreditForMercadopagoMapper.cs
Doppler.BillingUser/Mappers/BillingCredit/BillingCreditForTransferMapper.cs

Calculate the correct current month plan.

[DAT-1612] - Calculate the correct current month plan

---

Doppler.BillingUser/ApiModels/PaymentStatusApiEnum.cs
Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Enums/PaymentStatusEnum.cs
Doppler.BillingUser/Mappers/PaymentStatus/PaymentStatusMapper.cs

Task: [DAT-1631](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1631)
[DAT-1631]: https://makingsense.atlassian.net/browse/DAT-1631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-1631] fix: add new payment status

---

Doppler.BillingUser.Test/ReprocessTest.cs
Doppler.BillingUser/Controllers/BillingController.cs

Task: [DAT-1649](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1649)
[DAT-1649]: https://makingsense.atlassian.net/browse/DAT-1649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-1649] fix: add new payment status to reprocess endpoint

---

Doppler.BillingUser.Test/ReprocessTest.cs
Doppler.BillingUser/ApiModels/PaymentStatusApiEnum.cs
Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Enums/PaymentStatusEnum.cs
Doppler.BillingUser/Infrastructure/BillingRepository.cs
Doppler.BillingUser/Infrastructure/IBillingRepository.cs
Doppler.BillingUser/Mappers/AccountingEntry/AccountingEntryForCreditCardMapper.cs
Doppler.BillingUser/Mappers/AccountingEntry/AccountingEntryForMercadopagoMapper.cs
Doppler.BillingUser/Mappers/AccountingEntry/IAccountingEntryMapper.cs
Doppler.BillingUser/Mappers/PaymentStatus/PaymentStatusMapper.cs
Doppler.BillingUser/Model/BillingCreditPaymentInfo.cs
Doppler.BillingUser/Model/ImportedBillingDetail.cs
Doppler.BillingUser/Services/EmailTemplatesService.cs
Doppler.BillingUser/Services/IEmailTemplatesService.cs
Doppler.BillingUser/Utils/BillingHelper.cs

Allow to user change the payment method to MercadoPago when the user is canceled and the current payment method is Credit Card
**Task:** [DAT-1684](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1684)
[DAT-1684]: https://makingsense.atlassian.net/browse/DAT-1684?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-1684] - Integrate canceled account with mercado pago

---

Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Infrastructure/BillingRepository.cs
Doppler.BillingUser/Model/BillingCreditPaymentInfo.cs

Allow change the payment method to AR transfer when the user is canceled and it has CC or MP.
Task: [DAT-1709](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1709)
[DAT-1709]: https://makingsense.atlassian.net/browse/DAT-1709?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-1709] - Support change the payment method to AR transfer

---

Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Infrastructure/BillingRepository.cs
Doppler.BillingUser/Infrastructure/UserRepository.cs
Doppler.BillingUser/Mappers/BillingCredit/BillingCreditForAutomaticDebitMapper.cs
Doppler.BillingUser/Model/BillingCreditAgreement.cs
Doppler.BillingUser/Model/UserBillingInformation.cs

Supports buy plans with automatic debit in the checkout.
**Task:** [DAT-1718](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1718)
[DAT-1718]: https://makingsense.atlassian.net/browse/DAT-1718?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-1718] - Supports buy plans with automatic debit

---

Doppler.BillingUser.Test/ReprocessTest.cs
Doppler.BillingUser/Controllers/BillingController.cs

Support automatic debit when the user is cancelled
**Task:** [DAT-1695](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1695)
[DAT-1695]: https://makingsense.atlassian.net/browse/DAT-1695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-1695] - Support automatic debit when the user is cancelled

---

Doppler.BillingUser/ExternalServices/Clover/CloverService.cs

Try to show new message whent clover thowns an expected error.

[No-Ticket] - Try to show new message whent clover thowns an expected error

---

Dockerfile
Doppler.BillingUser.Test/Doppler.BillingUser.Test.csproj
Doppler.BillingUser/Doppler.BillingUser.csproj
Doppler.BillingUser/ExternalServices/Aws/AwsS3Service.cs
Doppler.BillingUser/ExternalServices/FirstData/PaymentGateway.cs

[No-task] update net 8

---

Doppler.BillingUser.Test/AccountPlansServiceTest.cs
Doppler.BillingUser/ExternalServices/AccountPlansApi/AccountPlansService.cs

Fix issue with timeout when call account plan api
**Task:** [DAT-1897](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1897)
[DAT-1897]: https://makingsense.atlassian.net/browse/DAT-1897?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-1897] - fix issue with timeout when call account plan api

---

Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Services/EmailTemplatesService.cs

Fix use with timeout when try to get the amount details.
**Task:** [DAT-1897](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1897)
[DAT-1897]: https://makingsense.atlassian.net/browse/DAT-1897?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-1897] - fix use with timeout when try to get the amount details

---

Doppler.BillingUser.Test/BuyLandingPlanTest.cs
Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Enums/BillingCreditTypeEnum.cs
Doppler.BillingUser/Enums/PlanTypeEnum.cs
Doppler.BillingUser/Enums/SourceTypeEnum.cs
Doppler.BillingUser/Infrastructure/BillingRepository.cs
Doppler.BillingUser/Infrastructure/IBillingRepository.cs
Doppler.BillingUser/Infrastructure/ILandingPlanUserRepository.cs
Doppler.BillingUser/Infrastructure/LandingPlanUserRepository.cs
Doppler.BillingUser/Mappers/BillingCredit/LandingPlan/BillingCreditForAutomaticDebitMapper.cs
Doppler.BillingUser/Mappers/BillingCredit/LandingPlan/BillingCreditForCreditCardMapper.cs
Doppler.BillingUser/Mappers/BillingCredit/LandingPlan/BillingCreditForMercadopagoMapper.cs
Doppler.BillingUser/Mappers/BillingCredit/LandingPlan/BillingCreditForTransferMapper.cs
Doppler.BillingUser/Mappers/BillingCredit/LandingPlan/IBillingCreditMapper.cs
Doppler.BillingUser/Model/BillingCreditModel.cs
Doppler.BillingUser/Model/BuyLandingPlans.cs
Doppler.BillingUser/Model/LandingPlan.cs
Doppler.BillingUser/Model/LandingPlanUser.cs
Doppler.BillingUser/Startup.cs

Crear endpoint para la contratación de packs de landing (Primera Compra)
**Tarea:** [](https://makingsense.atlassian.net/browse/DAT-1928)

[DAT-1928] - Crear endpoint para la contratación de packs de landing (Primera Compra)

---

Doppler.BillingUser/appsettings.json

Update prod config to use clover api.
**Task:** [DAT-1950](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1950)
[DAT-1950]: https://makingsense.atlassian.net/browse/DAT-1950?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-1950] - Update prod config to use clover api

---

Doppler.BillingUser/appsettings.json

[No-Ticket] - Change config to use FD

---

Doppler.BillingUser/appsettings.int.json
Doppler.BillingUser/appsettings.json
Doppler.BillingUser/appsettings.qa.json

Fix timeout issue when call internal apis. For it we used the service's name instead of the full path of the api.
**Task:** [DAT-1966](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1966)
[DAT-1966]: https://makingsense.atlassian.net/browse/DAT-1966?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-1966] - Fix timeout issue when call internal apis

---

Doppler.BillingUser/appsettings.json

[No-Task] - Use FD instead of Clover

---

Doppler.BillingUser.Test/BuyLandingPlanTest.cs
Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Enums/AdditionalServiceTypeEnum.cs
Doppler.BillingUser/ExternalServices/Sap/SapAdditionalServiceDto.cs
Doppler.BillingUser/ExternalServices/Sap/SapBillingDto.cs
Doppler.BillingUser/ExternalServices/Sap/SapPackDto.cs
Doppler.BillingUser/Infrastructure/BillingRepository.cs
Doppler.BillingUser/Utils/BillingHelper.cs
Doppler.BillingUser/appsettings.int.json

Integrate landing plans with sap
**Task:** [DAT-1977](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1977)
[DAT-1977]: https://makingsense.atlassian.net/browse/DAT-1977?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

 [DAT-1977] - Integrate landing plans with sap

---

Doppler.BillingUser.Test/LandingCancelationTest.cs
Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Exceptions/SessionExpiredException.cs
Doppler.BillingUser/ExternalServices/DopplerApi/DopplerMvcService.cs
Doppler.BillingUser/ExternalServices/DopplerApi/DopplerSettings.cs
Doppler.BillingUser/ExternalServices/DopplerApi/IDopplerMvcService.cs
Doppler.BillingUser/ExternalServices/DopplerApi/LandingPagesResponse.cs
Doppler.BillingUser/Infrastructure/BillingRepository.cs
Doppler.BillingUser/Infrastructure/IBillingRepository.cs
Doppler.BillingUser/Infrastructure/ILandingPlanUserRepository.cs
Doppler.BillingUser/Infrastructure/IUserAddOnRepository.cs
Doppler.BillingUser/Infrastructure/LandingPlanUserRepository.cs
Doppler.BillingUser/Infrastructure/UserAddOnRepository.cs
Doppler.BillingUser/Model/UserAddOn.cs
Doppler.BillingUser/Startup.cs
Doppler.BillingUser/appsettings.Development.json
Doppler.BillingUser/appsettings.int.json
Doppler.BillingUser/appsettings.json
Doppler.BillingUser/appsettings.qa.json

Task: [DAT-1996](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1996)
[DAT-1996]: https://makingsense.atlassian.net/browse/DAT-1996?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Dat 1996 - Cancellation of landing plans

---

Doppler.BillingUser/ExternalServices/Sap/SapAdditionalServiceDto.cs
Doppler.BillingUser/Utils/BillingHelper.cs

[No-Ticket] Fix issue to get discount

---

Doppler.BillingUser/appsettings.qa.json

[No-Ticket] Not use clover in qa

---

Doppler.BillingUser/Controllers/BillingController.cs

Show message in slack channel when the buy landing plans was successful

[No-ticket] Show message in slack channel when the buy landing plans was successful

---

Doppler.BillingUser/Infrastructure/BillingRepository.cs

Only get the pending invoices 
Task: [DAT-2075](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2075)
[DAT-2075]: https://makingsense.atlassian.net/browse/DAT-2075?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-2075] - Only get the pending invoices 

---

Doppler.BillingUser/ExternalServices/BeplicApi/BeplicService.cs
Doppler.BillingUser/ExternalServices/BeplicApi/IBeplicService.cs
Doppler.BillingUser/ExternalServices/BeplicApi/Responses/PlanAssignResponse.cs
Doppler.BillingUser/ExternalServices/BeplicApi/Responses/PlanResponse.cs

Task: [DAT-2103](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2103)
[DAT-2103]: https://makingsense.atlassian.net/browse/DAT-2103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-2103] Add assign plan to user in beplic service

---

Doppler.BillingUser/ExternalServices/BeplicApi/BeplicService.cs
Doppler.BillingUser/ExternalServices/BeplicApi/IBeplicService.cs
Doppler.BillingUser/ExternalServices/BeplicApi/Responses/PlanUnassignResponse.cs

Task: [DAT-2111](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2111)
[DAT-2111]: https://makingsense.atlassian.net/browse/DAT-2111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-2111] Add unassing plan to user method

---

Doppler.BillingUser.Test/GetCurrentPlanTest.cs
Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/ExternalServices/Sap/SapAdditionalServiceDto.cs
Doppler.BillingUser/Mappers/BillingCredit/AddOns/BillingCreditForAutomaticDebitMapper.cs
Doppler.BillingUser/Mappers/BillingCredit/AddOns/BillingCreditForMercadopagoMapper.cs
Doppler.BillingUser/Mappers/BillingCredit/AddOns/BillingCreditForTransferMapper.cs
Doppler.BillingUser/Model/CurrentPlan.cs
Doppler.BillingUser/Utils/BillingHelper.cs

Remove condition to check credit card
Task: [DAT-2102](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2102)
[DAT-2102]: https://makingsense.atlassian.net/browse/DAT-2102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

 [DAT-2102] Remove condition to check credit card

---

Doppler.BillingUser.Test/GetCurrentPlanTest.cs
Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/ExternalServices/AccountPlansApi/AccountPlansService.cs
Doppler.BillingUser/ExternalServices/AccountPlansApi/AccountPlansSettings.cs
Doppler.BillingUser/ExternalServices/AccountPlansApi/IAccountPlansService.cs
Doppler.BillingUser/ExternalServices/EmailSender/EmailNotificationsConfiguration.cs
Doppler.BillingUser/Infrastructure/ChatPlanUserRepository.cs
Doppler.BillingUser/Model/CurrentPlan.cs
Doppler.BillingUser/Services/EmailTemplatesService.cs
Doppler.BillingUser/Services/IEmailTemplatesService.cs
Doppler.BillingUser/appsettings.Development.json
Doppler.BillingUser/appsettings.int.json
Doppler.BillingUser/appsettings.json
Doppler.BillingUser/appsettings.qa.json

Send to the admin email when the user buys a conversations plan
Task: [DAT-2128](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2128)
[DAT-2128]: https://makingsense.atlassian.net/browse/DAT-2128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-2128] - Send to the admin email when the user buys a conversations plan

---

Doppler.BillingUser/appsettings.qa.json

change SAP url in the qa environment

[No-Ticket] change SAP url in the qa environment

---

Doppler.BillingUser/Controllers/BillingController.cs

Fix issue when save the conversation plan

[No-Ticket] Fix issue when save the conversation plan

---

Doppler.BillingUser/Infrastructure/UserAddOnRepository.cs

Fix issue when save addon for chat

[No-Ticket ]- Fix issue when save addon for chat

---

Doppler.BillingUser/Controllers/BillingController.cs

Only assign the plan is the user is not pending upgrade
**Task:** [DAT-2153](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2153)
[DAT-2153]: https://makingsense.atlassian.net/browse/DAT-2153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-2153] - Only assign the plan is the user is not pending upgrade

---

Doppler.BillingUser/Validators/AgreementInformationValidator.cs

Support buy only chat plan
**Task:** [DAT-2152](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2152)
[DAT-2152]: https://makingsense.atlassian.net/browse/DAT-2152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-2152] - Support buy only chat plan

---

Doppler.BillingUser/Utils/BillingHelper.cs

fix issue calculate update marketing plan

[no-task] fix issue calculate update marketing plan

---

Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Utils/BillingHelper.cs

Fix issue when send information to sap

[no-task] - Fix issue when send information to sap

---

Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/ExternalServices/Sap/SapAdditionalServiceDto.cs
Doppler.BillingUser/Model/AdditionalService.cs

Send IsCustom plan to sap
**Task:** [DAT-2210](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2210)
[DAT-2210]: https://makingsense.atlassian.net/browse/DAT-2210?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-2210] - Send IsCustom plan to sap

---

Doppler.BillingUser.Test/BillingControllerTest.cs
Doppler.BillingUser.Test/PostAgreementTest.cs
Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Enums/AccountTypeEnum.cs
Doppler.BillingUser/Enums/UserTypeEnum.cs
Doppler.BillingUser/Infrastructure/ClientManagerRepository.cs
Doppler.BillingUser/Infrastructure/IClientManagerRepository.cs
Doppler.BillingUser/Infrastructure/UserRepository.cs
Doppler.BillingUser/Mappers/AccountingEntry/AccountingEntryForCreditCardMapper.cs
Doppler.BillingUser/Mappers/AccountingEntry/AccountingEntryForMercadopagoMapper.cs
Doppler.BillingUser/Mappers/AccountingEntry/IAccountingEntryMapper.cs
Doppler.BillingUser/Mappers/BillingCredit/AddOns/BillingCreditForCreditCardMapper.cs
Doppler.BillingUser/Model/User.cs
Doppler.BillingUser/Model/UserBillingInformation.cs
Doppler.BillingUser/Startup.cs

Support buy conversations plan to CM user from Admin
**Task:** [DAT-2203](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2203)
[DAT-2203]: https://makingsense.atlassian.net/browse/DAT-2203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-2203] - Support buy conversations plan to CM user from Admin

---

Doppler.BillingUser/Controllers/BillingController.cs

fix issue when the conversation plan is updated

[No-Ticket] fix issue when the conversation plan is updated

---

Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/ExternalServices/Sap/SapAdditionalServiceDto.cs
Doppler.BillingUser/Utils/BillingHelper.cs

Add email property in addionalservice object
**Task:** [DAT-2242](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2242)
[DAT-2242]: https://makingsense.atlassian.net/browse/DAT-2242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-2242] - Add email property in addionalservice object

---

Doppler.BillingUser.Test/BuyOnSitePlanTest.cs
Doppler.BillingUser.Test/GetCurrentPlanTest.cs
Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Enums/AddOnType.cs
Doppler.BillingUser/Enums/BillingCreditTypeEnum.cs
Doppler.BillingUser/Enums/PlanTypeEnum.cs
Doppler.BillingUser/Enums/SourceTypeEnum.cs
Doppler.BillingUser/ExternalServices/EmailSender/EmailNotificationsConfiguration.cs
Doppler.BillingUser/Infrastructure/BillingRepository.cs
Doppler.BillingUser/Infrastructure/IBillingRepository.cs
Doppler.BillingUser/Infrastructure/IOnSitePlanRepository.cs
Doppler.BillingUser/Infrastructure/IOnSitePlanUserRepository.cs
Doppler.BillingUser/Infrastructure/OnSitePlanRepository.cs
Doppler.BillingUser/Infrastructure/OnSitePlanUserRepository.cs
Doppler.BillingUser/Mappers/OnSitePlan/IOnSitePlanUserMapper.cs
Doppler.BillingUser/Mappers/OnSitePlan/OnSitePlanUserMapper.cs
Doppler.BillingUser/Model/BuyOnSitePlan.cs
Doppler.BillingUser/Model/CurrentPlan.cs
Doppler.BillingUser/Model/OnSitePlan.cs
Doppler.BillingUser/Model/OnSitePlanUser.cs
Doppler.BillingUser/Services/EmailTemplatesService.cs
Doppler.BillingUser/Services/IEmailTemplatesService.cs
Doppler.BillingUser/Startup.cs
Doppler.BillingUser/Validators/ValidationError.cs
Doppler.BillingUser/Validators/ValidationResult.cs
Doppler.BillingUser/appsettings.Development.json
Doppler.BillingUser/appsettings.int.json
Doppler.BillingUser/appsettings.json
Doppler.BillingUser/appsettings.qa.json

Create endpoint to support buy onsite plans for regular and cm users
Task: [DAT-2251](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2251)
[DAT-2251]: https://makingsense.atlassian.net/browse/DAT-2251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-2251] - Create endpoint to support buy onsite plans for regular and cm users

---

Doppler.BillingUser.Test/OnSiteCancellationTest.cs
Doppler.BillingUser/Controllers/BillingController.cs

Add endpoint to cancel onsite plan
**Task:** [DAT-227](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2270)
[DAT-227]: https://makingsense.atlassian.net/browse/DAT-227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-227] - Add endpoint to cancel onsite plan

---

Doppler.BillingUser/Controllers/BillingController.cs

Update endpoint to get current plan by type to include onsite plan

feat: update endpoint to get current plan by type to include onsite plan

---

Doppler.BillingUser.Test/BuyOnSitePlanTest.cs
Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Enums/AdditionalServiceTypeEnum.cs
Doppler.BillingUser/ExternalServices/Sap/SapAdditionalServiceDto.cs
Doppler.BillingUser/Utils/BillingHelper.cs

Send onsite plan to sap
**Task:** [DAT-2255](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2255)
[DAT-2255]: https://makingsense.atlassian.net/browse/DAT-2255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-2255] - Send onsite plan to sap

---

Doppler.BillingUser/Mappers/BillingCredit/AddOns/BillingCreditForTransferMapper.cs

fix issue when buy onsite plan with transfer

[No-task] - fix issue when buy onsite plan with transfer

---

Doppler.BillingUser/Infrastructure/BillingRepository.cs

Fix issue when misisng credit card information

[no-task] - Fix issue when misisng credit card information

---

Doppler.BillingUser/Infrastructure/BillingRepository.cs

Get information from billingcredits when the user is null

[no-task] - Get information from billingcredits when the user is null

---

Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Enums/BillingCreditTypeEnum.cs
Doppler.BillingUser/Infrastructure/BillingRepository.cs
Doppler.BillingUser/Infrastructure/IOnSitePlanRepository.cs
Doppler.BillingUser/Infrastructure/IUserAddOnRepository.cs
Doppler.BillingUser/Infrastructure/OnSitePlanRepository.cs
Doppler.BillingUser/Infrastructure/UserAddOnRepository.cs
Doppler.BillingUser/Infrastructure/UserRepository.cs
Doppler.BillingUser/Mappers/OnSitePlan/IOnSitePlanUserMapper.cs
Doppler.BillingUser/Mappers/OnSitePlan/OnSitePlanUserMapper.cs
Doppler.BillingUser/Model/OnSitePlan.cs
Doppler.BillingUser/Model/OnSitePlanUser.cs
Doppler.BillingUser/Model/User.cs

Add endpoint to activate onsite plan
**Task:** [DAT-2309](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2309)
[DAT-2309]: https://makingsense.atlassian.net/browse/DAT-2309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-2309] - Add endpoint to activate onsite plan

---

Doppler.BillingUser.Test/BuyOnSitePlanTest.cs
Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/ExternalServices/Clover/CloverService.cs

[no-task] Fix issue cm

---

Doppler.BillingUser/ExternalServices/Clover/CloverService.cs

Add null check

---

Doppler.BillingUser.Test/PutCurrentPaymentMethodTest.cs
Doppler.BillingUser.Test/SanitizeCreditCardNumberTest.cs
Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/ExternalServices/BinApi/BinService.cs
Doppler.BillingUser/ExternalServices/BinApi/IBinService.cs
Doppler.BillingUser/Utils/CreditCardHelper.cs

Credit card schema filter

---

Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/ExternalServices/Sap/ISapService.cs
Doppler.BillingUser/ExternalServices/Sap/SapBillingUpdateDto.cs
Doppler.BillingUser/ExternalServices/Sap/SapService.cs
Doppler.BillingUser/ExternalServices/Sap/SapSettings.cs
Doppler.BillingUser/Infrastructure/UserRepository.cs
Doppler.BillingUser/appsettings.json

Send billing update to sap when the user process the invoices from the app.
**Task:** [DAT-2370](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2370)
[DAT-2370]: https://makingsense.atlassian.net/browse/DAT-2370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-2370] - Send billing update to sap when the user process the invoices from the app

---

Doppler.BillingUser/Controllers/WebhooksController.cs

[no-task] fix issue when assing status

---

Doppler.BillingUser/Controllers/WebhooksController.cs

[no-task] - Update url for the webhook

---

Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Enums/AddOnType.cs
Doppler.BillingUser/Infrastructure/BillingRepository.cs
Doppler.BillingUser/Infrastructure/IBillingRepository.cs
Doppler.BillingUser/Infrastructure/IPushNotificationPlanRepository.cs
Doppler.BillingUser/Infrastructure/PushNotificationPlanRepository.cs
Doppler.BillingUser/Mappers/AddOn/AddOnPlanUser.cs
Doppler.BillingUser/Mappers/AddOn/IAddOnMapper.cs
Doppler.BillingUser/Mappers/AddOn/OnSite/OnSiteMapper.cs
Doppler.BillingUser/Mappers/AddOn/PushNotification/PushNotificationMapper.cs
Doppler.BillingUser/Model/AddOnPlan.cs
Doppler.BillingUser/Model/PushNotificationPlan.cs
Doppler.BillingUser/Model/PushNotificationPlanUser.cs
Doppler.BillingUser/Startup.cs

Add logic to support activate for the all addon.
Task: [DAT-2449](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2449)
[DAT-2449]: https://makingsense.atlassian.net/browse/DAT-2449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-2449] - Add logic to support activate for the all addon

---

Doppler.BillingUser.Test/ActivateAddOnTest.cs
Doppler.BillingUser.Test/BuyAddOnPlanTest.cs
Doppler.BillingUser.Test/GetCurrentPlanTest.cs
Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Enums/BillingCreditTypeEnum.cs
Doppler.BillingUser/Enums/PlanTypeEnum.cs
Doppler.BillingUser/Enums/SourceTypeEnum.cs
Doppler.BillingUser/Infrastructure/IPushNotificationPlanUserRepository.cs
Doppler.BillingUser/Infrastructure/PushNotificationPlanUserRepository.cs
Doppler.BillingUser/Infrastructure/UserRepository.cs
Doppler.BillingUser/Mappers/AddOn/IAddOnMapper.cs
Doppler.BillingUser/Mappers/AddOn/OnSite/OnSiteMapper.cs
Doppler.BillingUser/Mappers/AddOn/PushNotification/PushNotificationMapper.cs
Doppler.BillingUser/Model/BuyAddOnPlan.cs
Doppler.BillingUser/Model/CurrentPlan.cs
Doppler.BillingUser/Startup.cs
Doppler.BillingUser/Utils/BillingHelper.cs

Update endpoint to supports buy push notification plan
**Task:** [DAT-2426](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2426)
[DAT-2426]: https://makingsense.atlassian.net/browse/DAT-2426?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-2426] - Update endpoint to supports buy push notification plan

---

Doppler.BillingUser/Controllers/BillingController.cs

Include push notification plan
**Task:** [DAT-2432](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2432)
[DAT-2432]: https://makingsense.atlassian.net/browse/DAT-2432?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-2432] - Include push notification plan

---

Doppler.BillingUser.Test/AddOnCancellationTest.cs
Doppler.BillingUser/Controllers/BillingController.cs

Task: [DAT-2465](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2465)
[DAT-2465]: https://makingsense.atlassian.net/browse/DAT-2465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-2465]

---

Doppler.BillingUser/Mappers/BillingCredit/AddOns/BillingCreditForAutomaticDebitMapper.cs
Doppler.BillingUser/Mappers/BillingCredit/AddOns/BillingCreditForMercadopagoMapper.cs
Doppler.BillingUser/Mappers/BillingCredit/AddOns/BillingCreditForTransferMapper.cs

fix issue when set data from billinguserdata

feat: fix issue when set data from billinguserdata

---

Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Mappers/AddOn/PushNotification/PushNotificationMapper.cs

Integrate email with buy push notification plan.
**Task:** [DAT-2464](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2464)
[DAT-2464]: https://makingsense.atlassian.net/browse/DAT-2464?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-2464] - Integrate email with buy push notification plan

---

Doppler.BillingUser.Test/BuyAddOnPlanTest.cs
Doppler.BillingUser/Controllers/BillingController.cs

Send incorrect date when send to sap the onsite plan.

[no-task] - Send incorrect date when send to sap the onsite plan

---

Doppler.BillingUser/Mappers/BillingCredit/BillingCreditForAutomaticDebitMapper.cs
Doppler.BillingUser/Mappers/BillingCredit/BillingCreditForCreditCardMapper.cs
Doppler.BillingUser/Mappers/BillingCredit/BillingCreditForMercadopagoMapper.cs
Doppler.BillingUser/Mappers/BillingCredit/BillingCreditForTransferMapper.cs

fix issue to set promotion duration

[no-task] - fix issue to set promotion duration

---

Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Utils/SourceTypeHelper.cs

Fix issue when the user buy conversation and individual plan.
**Task:** [DAT-2484](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62/backlog?selectedIssue=DAT-2484)
[DAT-2484]: https://makingsense.atlassian.net/browse/DAT-2484?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-2484] - Fix issue when the user buy conversation and individual plan

---

Doppler.BillingUser/Controllers/BillingController.cs
Doppler.BillingUser/Infrastructure/IUserAddOnRepository.cs
Doppler.BillingUser/Infrastructure/UserAddOnRepository.cs

Create endpoint to cancel all addon for the user
**Task:** [DAT-2587](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2587)
[DAT-2587]: https://makingsense.atlassian.net/browse/DAT-2587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-2587] - Create endpoint to cancel all addon for the user

---

Doppler.BillingUser/appsettings.json

[no-task] - Use clover api

---

Doppler.BillingUser/appsettings.int.json
Doppler.BillingUser/appsettings.json
Doppler.BillingUser/appsettings.qa.json

Update template for the notification

[DAT-2592] - Update template for the notification

---

Doppler.BillingUser/appsettings.json

Update ids for the new cancellation reason

[no-task] - Update ids for the new cancellation reason

---

Doppler.BillingUser/Controllers/BillingController.cs

Supports credits plan to cancel the account

[no-task] - Supports credits plan to cancel the account

---

Doppler.BillingUser/appsettings.qa.json

Change map for free users in the qa environment

[no-task] - Change map for free users in the qa environment

---

Doppler.BillingUser/appsettings.qa.json

Change email for the cutomer experience for the qa environment

[no-task] - Change email for the cutomer experience for the qa environment
