FromDoppler/doppler-billing-user

- Doppler.BillingUser.Test/AuthorizationTest.cs
- Doppler.BillingUser.Test/Doppler.BillingUser.Test.csproj
- Doppler.BillingUser.Test/GetBillingInformationTest.cs
- Doppler.BillingUser.Test/Utils/ServiceCollectionExtensions.cs
- Doppler.BillingUser/Controllers/BillingController.cs
- Doppler.BillingUser/Doppler.BillingUser.csproj
- Doppler.BillingUser/Infrastructure/BillingRepository.cs
- Doppler.BillingUser/Infrastructure/DatabaseConnectionFactory.cs
- Doppler.BillingUser/Infrastructure/DopplerDatabaseSettings.cs
- Doppler.BillingUser/Infrastructure/IBillingRepository.cs
- Doppler.BillingUser/Infrastructure/IDatabaseConnectionFactory.cs
- Doppler.BillingUser/Infrastructure/InfrastructureServiceCollectionExtensions.cs
- Doppler.BillingUser/Model/BillingInformation.cs
- Doppler.BillingUser/Startup.cs
- Doppler.BillingUser/appsettings.Development.json
- Doppler.BillingUser/appsettings.json
Here is added a new endpoint, in order to get the user billing information:
```
{
firstname: string;
lastname: string;
address: string;
city: string;
province: string;
country: string;
zipCode: string;
phone: string;
}
```
*We used a JSON for the security questions that it was save in cdn:
- ES: https://cdn.fromdoppler.com/static-data/questions-es.json
- EN: https://cdn.fromdoppler.com/static-data/questions-en.json
> [DAT-511] - Add endpoint to get billing information 

- Doppler.BillingUser.Test/AuthorizationTest.cs
- Doppler.BillingUser.Test/GetCurrentPaymentMethodTest.cs
- Doppler.BillingUser/Controllers/BillingController.cs
- Doppler.BillingUser/Encryption/EncryptionService.cs
- Doppler.BillingUser/Encryption/EncryptionSettings.cs
- Doppler.BillingUser/Encryption/IEncryptionService.cs
- Doppler.BillingUser/Infrastructure/BillingRepository.cs
- Doppler.BillingUser/Infrastructure/IBillingRepository.cs
- Doppler.BillingUser/Model/PaymentMethod.cs
- Doppler.BillingUser/Startup.cs
- Doppler.BillingUser/Utils/CreditCardHelper.cs
We need support for Transfers, Credit card’s and Mercadopago to get information about the Payment method
endpoint  `Get /accounts/{username}/payment-methods/current`
return
```
{
"ccHolderFullName": "Lorena Motta",
"ccNumber": "************4916",
"ccVerification": "***",
"ccExpMonth": "6",
"ccExpYear": "2025",
"ccType": "Visa",
"paymentMethodName": "MP",
"renewalMonth": "1",
"razonSocial": null,
"idConsumerType": "1",
"identificationType": "DNI",
"identificationNumber": "29435331"
}
```
> feat: [DAT-538] Add Get current payment method endpoint

- Doppler.BillingUser.Test/GetCurrentPaymentMethodTest.cs
- Doppler.BillingUser/Infrastructure/BillingRepository.cs
- Doppler.BillingUser/Model/PaymentMethod.cs
We save ResponsableIVA in user table for Colombia country and the rest of the country
Example:
`{
"paymentMethodName": "TRANSF",
"ccType": "unknown",
"idSelectedPlan": "13",
"razonSocial": "",
"idConsumerType": "CF",
"identificationNumber": "12345678",
"responsableIVA": false
}`
> feat: [DAT-673] Add ResponsableIVA property for Colombia

- Doppler.BillingUser.Test/GetInvoiceRecipientsTest.cs
- Doppler.BillingUser/Infrastructure/BillingRepository.cs
when user-> BillingEmails is empty, the get email recipients endpoint should be return [] by [""]
Example:
> fix: [DAT-625] Fix Get email recipients empty

- Doppler.BillingUser.Test/PutInvoiceRecipientsTest.cs
- Doppler.BillingUser/Controllers/BillingController.cs
- Doppler.BillingUser/ExternalServices/Sap/SapHelper.cs
- Doppler.BillingUser/Infrastructure/BillingRepository.cs
- Doppler.BillingUser/Infrastructure/IBillingRepository.cs
- Doppler.BillingUser/Infrastructure/InfrastructureServiceCollectionExtensions.cs
- Doppler.BillingUser/Model/InvoiceRecipients.cs
We need to set email invoice recipients in User->BillingEmails and if correspond to send to SAP
Pseudocode:
if user is QBL or BBISIDE billing System, the system sends to sap with the information to create a new BP
contract:
```
accounts/{accountName}/billing-information/invoice-recipients (PUT) Body: {
{
"planId": 11,
"recipients": [
"test20@mailinator.com", 
"test21@mailinator.com"
]
}
}
```
> feat: [DAT-625] Add PUT email recipients endpoint

- Doppler.BillingUser/web.config
Hi team!
We need to accept URLs like: `http://{host}/accounts/test1+extra@test.com/billing-information`
Right now we are getting this error:
See [related chat](https://makingsense.slack.com/archives/CRXR62TC2/p1637329152092200).
Since in test and production environments we are using Linux containers with Kestrel behind Traefik, this change should not affect there. It neither affects our unit tests.
Probably we should apply this same patch in other projects.
> chore: allow to deal with plus symbol (+) in local IIS Express developer environment

- Doppler.BillingUser/ExternalServices/Sap/ISapService.cs
- Doppler.BillingUser/ExternalServices/Sap/SapBillingDto.cs
- Doppler.BillingUser/ExternalServices/Sap/SapHelper.cs
- Doppler.BillingUser/ExternalServices/Sap/SapService.cs
- Doppler.BillingUser/ExternalServices/Sap/SapSettings.cs
- Doppler.BillingUser/appsettings.Development.json
- Doppler.BillingUser/appsettings.json
We send invoice information when user upgrades the account, the logic is similar that Doppler
endpoint `Billing/CreateBillingRequest`
body
`"[{\"Id\":1,\"PlanType\":0,\"CreditsOrSubscribersQuantity\":0,\"IsCustomPlan\":true,\"IsPlanUpgrade\":true,\"Currency\":0,\"Periodicity\":0,\"PeriodMonth\":1,\"PeriodYear\":1,\"PlanFee\":2.0,\"Discount\":0,\"ExtraEmails\":null,\"ExtraEmailsFeePerUnit\":null,\"ExtraEmailsPeriodMonth\":1,\"ExtraEmailsPeriodYear\":1,\"ExtraEmailsFee\":0.0,\"PurchaseOrder\":null,\"FiscalID\":null,\"BillingSystemId\":0,\"CardHolder\":\"CcHolderName\",\"CardType\":null,\"CardNumber\":null,\"CardErrorCode\":\"100\",\"CardErrorDetail\":\"Successfully approved\",\"TransactionApproved\":false,\"TransferReference\":\"678\",\"InvoiceId\":23,\"DiscountedAmount\":null,\"IsFirstPurch …
> feat: [DAT-670] Send invoice to Sap

- Doppler.BillingUser.Test/GetCurrentPlanTest.cs
- Doppler.BillingUser.Test/SapServiceTest.cs
- Doppler.BillingUser/Controllers/BillingController.cs
- Doppler.BillingUser/ExternalServices/Sap/SapService.cs
- Doppler.BillingUser/Infrastructure/BillingRepository.cs
- Doppler.BillingUser/Infrastructure/IBillingRepository.cs
- Doppler.BillingUser/Model/CurrentPlan.cs
We need a Get current plan endpoint to get current plan information to Summary page plan
example:
`accounts/{accountname}/plans/current`
response
```
{
"idPlan": 2,
"planSubscription": 0,
"planType": "Individual",
"remainingCredits": 19500,
"emailQty": 2500,
"subscribersQty": null
}
```
In additional, fix generator token for sap service
> feat: [DAT-714] Add GET current plan endpoint

- Doppler.BillingUser.Test/PostAgreementTest.cs
- Doppler.BillingUser/Controllers/BillingController.cs
- Doppler.BillingUser/ExternalServices/AccountPlansApi/AccountPlansService.cs
- Doppler.BillingUser/ExternalServices/AccountPlansApi/AccountPlansSettings.cs
- Doppler.BillingUser/ExternalServices/AccountPlansApi/IAccountPlansService.cs
- Doppler.BillingUser/Infrastructure/BillingRepository.cs
- Doppler.BillingUser/Infrastructure/IBillingRepository.cs
- Doppler.BillingUser/Model/Promotion.cs
- Doppler.BillingUser/appsettings.Development.json
- Doppler.BillingUser/appsettings.int.json
- Doppler.BillingUser/appsettings.json
- Doppler.BillingUser/appsettings.qa.json
We need to save the IdPromotion in BillingCredits table when the user buys a new plan with promocode valid
Steps:
1- The user clicks on the Buy button, the system triggers a POST request to Billing user API
2- Billing user API make a request of the promocode values of agreement, sending a GET request to Account Plans API
3- Account plans API processes the petition, getting the promocode of agreement with information saved in the Doppler database
4- Account plans API return promocode information to Billing API user to use these values
5- Billing user API saves the promocodeId in the billing credit table
6- Billing user API sends reponse to WebApp
> feat: [DAT-702] Save promotionId in billingCredits

- Doppler.BillingUser.Test/PostAgreementTest.cs
- Doppler.BillingUser/Controllers/BillingController.cs
- Doppler.BillingUser/ExternalServices/EmailSender/EmailNotificationsConfiguration.cs
- Doppler.BillingUser/ExternalServices/EmailSender/RelayEmailSenderSettings.cs
- Doppler.BillingUser/Infrastructure/IUserRepository.cs
- Doppler.BillingUser/Infrastructure/UserRepository.cs
- Doppler.BillingUser/Model/Promotion.cs
- Doppler.BillingUser/Model/User.cs
- Doppler.BillingUser/Model/UserTypePlanInformation.cs
- Doppler.BillingUser/Startup.cs
- Doppler.BillingUser/appsettings.Development.json
- Doppler.BillingUser/appsettings.int.json
- Doppler.BillingUser/appsettings.json
- Doppler.BillingUser/appsettings.qa.json
Here we are adding the sending of email by Relay email sender to the User and to the Admin when a credits purchase is sucessfull. Three templates have been created in Relay, in the test user: dopplerrelay+test@makingsense.com
- Credits approved to User in english: **3b1da2c0-124f-4df9-b588-ef54e8e9aec8**
- Credits approved to User in spanish: **a8d0afca-f8e8-4ef0-be1a-1ec3edacbe51**
- Credits approved to Admin (is always in spanish): **0bc86e98-0e96-4f5f-be67-f62e17b46afa**
WIP: unit test missing
> [DAT-708] - Add email notification when the credits purchase is successful

- Doppler.BillingUser/appsettings.qa.json
Here we are changing the account Admin for QA environment, in order to the people that make the tests can check it.
> [DAT-708]: Change admin email in QA env

- Doppler.BillingUser.Test/PostAgreementTest.cs
- Doppler.BillingUser.Test/ZohoServiceTest.cs
- Doppler.BillingUser/Controllers/BillingController.cs
- Doppler.BillingUser/ExternalServices/Zoho/API/ZohoEntityAccount.cs
- Doppler.BillingUser/ExternalServices/Zoho/API/ZohoEntityBase.cs
- Doppler.BillingUser/ExternalServices/Zoho/API/ZohoEntityContact.cs
- Doppler.BillingUser/ExternalServices/Zoho/API/ZohoEntityLead.cs
- Doppler.BillingUser/ExternalServices/Zoho/API/ZohoRefreshTokenResponse.cs
- Doppler.BillingUser/ExternalServices/Zoho/API/ZohoResponse.cs
- Doppler.BillingUser/ExternalServices/Zoho/API/ZohoResponseInfo.cs
- Doppler.BillingUser/ExternalServices/Zoho/API/ZohoUpdateModel.cs
- Doppler.BillingUser/ExternalServices/Zoho/API/ZohoUpdateResponse.cs
- Doppler.BillingUser/ExternalServices/Zoho/API/ZohoUpdateResponseDetail.cs
- Doppler.BillingUser/ExternalServices/Zoho/API/ZohoUpdateResponseItem.cs
- Doppler.BillingUser/ExternalServices/Zoho/API/ZohoUser.cs
- Doppler.BillingUser/ExternalServices/Zoho/IZohoService.cs
- Doppler.BillingUser/ExternalServices/Zoho/ZohoDTO.cs
- Doppler.BillingUser/ExternalServices/Zoho/ZohoService.cs
- Doppler.BillingUser/ExternalServices/Zoho/ZohoSettings.cs
- Doppler.BillingUser/Startup.cs
- Doppler.BillingUser/appsettings.Development.json
- Doppler.BillingUser/appsettings.int.json
- Doppler.BillingUser/appsettings.json
- Doppler.BillingUser/appsettings.qa.json
Send update request to zoho api when agreement creation is successfully completed, only if the "UseZoho" flag is true in the app.settings.
**Notes:** 
- If the zoho api request throws an exception, it is caught and a notification is sent to the slack channel.
- Only in production configuration the flag has to be true, for others it must be false.
> Dat 625 billing user api   integrar con zoho

- Doppler.BillingUser/appsettings.json
Set Relay templates IDs for email notifications when the user do a credit purchase, for production environment.
> [NO-TICKET] - Set templates id for email notification

- Doppler.BillingUser/Infrastructure/BillingRepository.cs
- Doppler.BillingUser/Infrastructure/UserRepository.cs
- Doppler.BillingUser/Model/UserBillingInformation.cs
When the "BillingCredit' is created some information is wrong. For example: Description, Plan and Credits.
Before:
After:
**Task:** [DAT-779](https://makingsense.atlassian.net/browse/DAT-779)
> [DAT-779] - Fix issue when the 'BillingCredit' is created

- Doppler.BillingUser.Test/Utils/ServiceCollectionExtensions.cs
- Doppler.BillingUser/Infrastructure/BillingRepository.cs
- Doppler.BillingUser/Infrastructure/DatabaseConnectionFactory.cs
- Doppler.BillingUser/Infrastructure/IDatabaseConnectionFactory.cs
- Doppler.BillingUser/Infrastructure/PromotionRepository.cs
- Doppler.BillingUser/Infrastructure/UserRepository.cs
It is not necessary to open the connection explicitly, dapper will do it when a query is executed.
Based in fix (https://github.com/FromDoppler/doppler-html-editor-api/pull/42)
> fix: do not open connection on factory

- Doppler.BillingUser/appsettings.json
Update relay account to use leve2support.
**Task:** [DAT-812](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-812)
Notes:
The change of the Relay's account no affect the PROD environment because the emails are not sending at the moment in the PROD environment.
> [DAT-812] - Update relay account to use leve2support

- Doppler.BillingUser/Infrastructure/BillingRepository.cs
- Doppler.BillingUser/Infrastructure/IBillingRepository.cs
We need to create a method on `BillingRespository` to insert a paymentEntry into DB to achive the flow at the bottom of this comment.
- https://github.com/FromDoppler/doppler-billing-user/pull/176
- https://github.com/FromDoppler/doppler-billing-user/pull/174
- _CreatePaymentEntryAsync_ method was added in `BillingRepository`.
```mermaid
sequenceDiagram
participant MercadoPago
participant MercadoPagoAPI
participant BillingUserAPI
participant BillingUserDB
MercadoPago ->> BillingUserAPI: POST "/doppler-billing-user/Integration/{accountname}/MercadopagoNotification"
BillingUserAPI->>MercadoPagoAPI: Get payment
MercadoPagoAPI->>MercadoPago: Get payment
MercadoPago->>MercadoPagoAPI: Payment info
MercadoPagoAPI->>BillingUserAPI: Payment info
BillingUserAPI->>BillingUserDB: Get invoice …
```
> [DAT-952] - Add create payment method

- Doppler.BillingUser/Infrastructure/BillingRepository.cs
- Doppler.BillingUser/Infrastructure/IBillingRepository.cs
We need to create the GetInvoice method to get the invoice by customer and payment ID.
This code is part of the next flow:
```mermaid
sequenceDiagram
participant MercadoPago
participant MercadoPagoAPI
participant BillingUserAPI
participant BillingUserDB
MercadoPago ->> BillingUserAPI: POST "/doppler-billing-user/Integration/{accountname}/MercadopagoNotification"
BillingUserAPI->>MercadoPagoAPI: Get payment
MercadoPagoAPI->>MercadoPago: Get payment
MercadoPago->>MercadoPagoAPI: Payment info
MercadoPagoAPI->>BillingUserAPI: Payment info
BillingUserAPI->>BillingUserDB: Get invoice (BillingRepo)
BillingUserDB->>BillingUserAPI: Invoice info
BillingUserAPI->>BillingUserDB: Update invoice (BillingRepo)
BillingUserAPI->>BillingUserDB: Get CreditCard (UserRepo)
BillingUserDB->>BillingUserAPI: CC …
```
> [DAT-950] - Add GetInvoice method

- Doppler.BillingUser.Test/MercadoPagoServiceTest.cs
- Doppler.BillingUser/ExternalServices/MercadoPagoApi/IMercadoPagoService.cs
- Doppler.BillingUser/ExternalServices/MercadoPagoApi/MercadoPagoPayment.cs
- Doppler.BillingUser/ExternalServices/MercadoPagoApi/MercadoPagoService.cs
- Doppler.BillingUser/ExternalServices/MercadoPagoApi/MercadoPagoSettings.cs
- Doppler.BillingUser/Startup.cs
- Doppler.BillingUser/appsettings.Development.json
- Doppler.BillingUser/appsettings.int.json
- Doppler.BillingUser/appsettings.json
- Doppler.BillingUser/appsettings.qa.json
This service is created to use the MercadoPago API. 
It will be used to obtain the payment information, when the status is updated in MP and then it sends a notification with the payment id.
Related Pull Request:
- https://github.com/FromDoppler/doppler-billing-user/pull/176
- https://github.com/FromDoppler/doppler-billing-user/pull/174
- https://github.com/FromDoppler/doppler-billing-user/pull/177
- Add MercadoPagoService
```mermaid
sequenceDiagram
participant MercadoPago
participant MercadoPagoAPI
participant BillingUserAPI
participant BillingUserDB
MercadoPago ->> BillingUserAPI: POST "/doppler-billing-user/Integration/{accountname}/MercadopagoNotification"
BillingUserAPI->>MercadoPagoAPI: Get payment
MercadoPagoAPI->>MercadoPago: Get payment
MercadoPago->>MercadoPagoAPI: Payment info …
```
> [DAT-953] - Create Mercadopago Service

- Doppler.BillingUser/Infrastructure/BillingRepository.cs
- Doppler.BillingUser/Infrastructure/UserRepository.cs
Some DbConnections were implemented without the Using declaration in Billing and User Repositories.
> [DAT-969] Add missing usings

- Doppler.BillingUser/Infrastructure/UserRepository.cs
Bug fixed when upgrading an account with a free plan. Now keeps the old MaxSubscribers number if the new plan has SubscribersQty set in NULL.
Jira task [here](https://makingsense.atlassian.net/browse/DOM-390).
> [DOM-390] - max subscribers zero on upgrade

- Doppler.BillingUser/Controllers/BillingController.cs
Currently when the billing team approves the payment the credits are duplicated wrongly.
**Issue:** [DAT-1182](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1182)
> [DAT-1182] - Wrong duplicate credits

- Doppler.BillingUser.Test/PostAgreementTest.cs
- Doppler.BillingUser/Controllers/BillingController.cs
Add last four digits in the error message when first data throws an error.
**Error message:**
- Failed at updating payment method for user test_show_credit_card_slack_error_int_1@mailinator.com with last four digits of the credit card: 4444. Exception DeclinedPaymentTransaction - Invalid Credit Card Number.
- Failed at creating new agreement for user test_show_credit_card_slack_error_int_1@mailinator.com with last four digits of the credit card: 1111. Exception DeclinedPaymentTransaction - Invalid Expiration Date [Bank]
**Task:**[DAT-1226](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1226)
> [DAT-1226] - Add last four digits in the error message when first data throws an error

- Doppler.BillingUser/Services/EmailTemplatesService.cs
[DAT-1378](https://makingsense.atlassian.net/browse/DAT-1378)
Add email field for the DECLINEDMERCADOPAGOPAYMENTUPSELLINGADMIN and DECLINEDMERCADOPAGOPAYMENTUPGRADEADMIN templates
[DAT-1378]: https://makingsense.atlassian.net/browse/DAT-1378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DAT-1378] - add email to declined mercadopago payment email

- Doppler.BillingUser/ExternalServices/FirstData/PaymentGateway.cs
- Doppler.BillingUser/Utils/XmlSerializer.cs
Use FlurlClient instead of SOAP Client when call FirstData because using SOAP Client we have an error:
Exception ClientPaymentTransactionError - The content type text/plain; charset=UTF-8 of the response message does not match the content type of the binding (text/xml; charset=utf-8). If using a custom encoder, be sure that the IsContentTypeSupported method is implemented properly. The first 1024 bytes of the response were: '<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><q2:Transaction id="id1" xsi:type="q2:Transaction" xmlns:q2="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/encodedTypes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><ExactID …
> [No-Ticket] Use FlurlClient instead of SOAP Client

- Doppler.BillingUser/Services/EmailTemplatesService.cs
Fix bug tax regime value in the email was only the tax regime Id instead of the description
> fix: send tax regime description

- Doppler.BillingUser.Test/ReprocessTest.cs
- Doppler.BillingUser/ApiModels/PaymentStatusApiEnum.cs
- Doppler.BillingUser/Controllers/BillingController.cs
- Doppler.BillingUser/Enums/PaymentStatusEnum.cs
- Doppler.BillingUser/Mappers/PaymentStatus/PaymentStatusMapper.cs
Add ClientPaymentTransactionError status in PaymentStatusEnum and include it to get invoices.
**Task:** [DAT-1527](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1527)
[DAT-1527]: https://makingsense.atlassian.net/browse/DAT-1527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DAT-1527] - Include ClientPaymentTransactionError status in PaymentStatusEnum
